//
// MessageAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class MessageAPI {
    public let apiConfiguration: MiraStreamingSDKAPIConfiguration
    public init(apiConfiguration: MiraStreamingSDKAPIConfiguration = MiraStreamingSDKAPIConfiguration.shared) {
        self.apiConfiguration = apiConfiguration
    }

    /**
     Delete inbox messages
     
     - parameter ids: (query) Comma-separated message IDs. 
     - returns: Void
     */
    open func deleteInboxMessages(ids: Set<UUID>) async throws(ErrorResponse) {
        return try await deleteInboxMessagesWithRequestBuilder(ids: ids).execute().body
    }

    /**
     Delete inbox messages
     - DELETE /message
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter ids: (query) Comma-separated message IDs. 
     - returns: RequestBuilder<Void> 
     */
    open func deleteInboxMessagesWithRequestBuilder(ids: Set<UUID>) -> RequestBuilder<Void> {
        let localVariablePath = "/message"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "ids": (wrappedValue: ids.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: false),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List received messages
     
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query) Values outside 0 through 300 fall back to 20. (optional, default to 20)
     - returns: PaginatedMessage
     */
    open func listInboxMessages(offset: Int? = nil, limit: Int? = nil) async throws(ErrorResponse) -> PaginatedMessage {
        return try await listInboxMessagesWithRequestBuilder(offset: offset, limit: limit).execute().body
    }

    /**
     List received messages
     - GET /message/inbox
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query) Values outside 0 through 300 fall back to 20. (optional, default to 20)
     - returns: RequestBuilder<PaginatedMessage> 
     */
    open func listInboxMessagesWithRequestBuilder(offset: Int? = nil, limit: Int? = nil) -> RequestBuilder<PaginatedMessage> {
        let localVariablePath = "/message/inbox"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "offset": (wrappedValue: offset?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedMessage>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List sent messages
     
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query) Values outside 0 through 300 fall back to 20. (optional, default to 20)
     - returns: PaginatedMessage
     */
    open func listSentMessages(offset: Int? = nil, limit: Int? = nil) async throws(ErrorResponse) -> PaginatedMessage {
        return try await listSentMessagesWithRequestBuilder(offset: offset, limit: limit).execute().body
    }

    /**
     List sent messages
     - GET /message/sent
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query) Values outside 0 through 300 fall back to 20. (optional, default to 20)
     - returns: RequestBuilder<PaginatedMessage> 
     */
    open func listSentMessagesWithRequestBuilder(offset: Int? = nil, limit: Int? = nil) -> RequestBuilder<PaginatedMessage> {
        let localVariablePath = "/message/sent"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "offset": (wrappedValue: offset?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedMessage>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Mark inbox messages as read
     
     - parameter requestBody: (body)  
     - returns: Void
     */
    open func markMessagesRead(requestBody: Set<UUID>) async throws(ErrorResponse) {
        return try await markMessagesReadWithRequestBuilder(requestBody: requestBody).execute().body
    }

    /**
     Mark inbox messages as read
     - PUT /message/read
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter requestBody: (body)  
     - returns: RequestBuilder<Void> 
     */
    open func markMessagesReadWithRequestBuilder(requestBody: Set<UUID>) -> RequestBuilder<Void> {
        let localVariablePath = "/message/read"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
