openapi: 3.0.3
components:
  securitySchemes:
    oAuth2:
      type: oauth2
      description: OAuth with Client Credentials Flow, Authorization Code Flow
      flows:
        authorizationCode:
          authorizationUrl: 'https://authorization.box.moe/oauth2/token'
          tokenUrl: 'https://authorization.box.moe/oauth2/token'
          scopes:
            bookmark: will grant application to access the user's bookmarks and reviews

security:
  - oAuth2:
      - bookmark
