openapi: 3.0.3
info:
  version: 1.0.0
  title: mira Favorite API
  description: Favorite API for Project-Mira
paths:
  /client-mapping:
    post:
      description: Add ClientMapping
      operationId: AddClientMapping
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: addClientMappingRequestBody
              type: array
              items:
                type: string
      responses:
        '200':
          description: Successfully added ClientMapping
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientMapping'
  /client-mapping/main/{id}:
    delete:
      description: Delete ClientMapping by MainItem id
      operationId: DeleteClientMappingByMainItemId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: return the result of the operation
          content:
            application/json:
              schema:
                title: DeleteClientMappingByMainItemResponse
                type: object
                required:
                  - data
                properties:
                  data:
                    type: integer
                    description: how many entries are deleted, 1 is successful, 0 is unsuccessful.
  /client-mapping/batch/main:
    post:
      operationId: batchGetMainItemByIdList
      description: get mainItems by id list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdListRequestBody'
      responses:
        '200':
          description: Successfully return a list of MainItems
          content:
            application/json:
              schema:
                title: batchGetMainItemByIdListResult
                type: object
                required:
                  - data
                properties:
                  data:
                    type: array
                    items:
                      $ref: './items.yaml#/components/schemas/MainItem'
  /client-mapping/batch/subItem:
    post:
      operationId: batchGetSubItemsByIdList
      description: get SubItems by id list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdListRequestBody'
      responses:
        '200':
          description: Successfully return a list of SubItems
          content:
            application/json:
              schema:
                title: batchGetSubItemByIdListResult
                type: object
                required:
                  - data
                properties:
                  data:
                    type: array
                    items:
                      $ref: './items.yaml#/components/schemas/SubItem'

components:
  schemas:
    ClientMapping:
      type: object
      required:
        - id
        - clientId
        - item
      properties:
        id:
          type: string
        clientId:
          type: string
        item:
          $ref: './items.yaml#/components/schemas/MainItem'
    IdListRequestBody:
      title: IdListRequestBody
      type: object
      required:
        - ids
      properties:
        ids:
          type: array
          items:
            type: string
