openapi: 3.0.3
info:
  version: 1.0.0
  title: mira Item API
  description: Item API for Project-Mira
paths:
  /public/item/on-air:
    get:
      description: get a list of on air MainItems with cover image
      operationId: onAirItem
      parameters:
        - name: type
          in: query
          required: true
          description: 'type of MainItem, must be either anime or real'
          schema:
            type: string
      responses:
        '200':
          description: Successfully returned a list of on air MainItems with cover image.
          content:
            application/json:
              schema:
                title: GetOnAirItemListResponse
                type: object
                required:
                  - data
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/OnAirItem'
                    description: a list of OnAirItems
  /public/item/main:
    get:
      description: list MainItems
      operationId: listMainItems
      parameters:
        - name: mainType
          in: query
          required: true
          schema:
            type: string
        - name: type
          in: query
          required: false
          schema:
            type: string
        - name: subType
          in: query
          required: false
          schema:
            type: string
        - name: offset
          in: query
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: orderBy
          in: query
          required: false
          schema:
            type: string
        - name: sort
          in: query
          required: false
          schema:
            type: string
        - name: keyword
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successfully return a list of MainItems and a total count of MainItems that match the condition
          content:
            application/json:
              schema:
                title: listMainItemResponse
                type: object
                required:
                  - data
                  - total
                  - status
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MainItem'
                    description: a list of MainItems
                  total:
                    type: integer
                    description: total number of the result
  /public/item/main/subItem/{id}:
    get:
      description: get a SubItem by id
      operationId: getSubItemById
      parameters:
        - name: id
          in: path
          required: true
          description: SubItem Id
          schema:
            type: string
      responses:
        '200':
          description: Successfully return a SubItem
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubItem'
  /public/item/main/{id}:
    get:
      description: get a MainItem by id
      operationId: getMainItemById
      parameters:
        - name: id
          in: path
          required: true
          description: MainItem id
          schema:
            type: string
        - name: coverImage
          in: query
          required: false
          description: populate coverImage if true
          schema:
            type: string
        - name: subItems
          in: query
          required: false
          description: populate subItems if true
          schema:
            type: string
      responses:
        '200':
          description: Successfully returned a MainItem.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MainItem'
  /public/item/batch/main:
    post:
      operationId: batchGetMainItemByIdList
      description: get mainItems by id list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdListRequestBody'
      responses:
        '200':
          description: Successfully return a list of MainItems
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MainItem'
  /public/item/batch/subItem:
    post:
      operationId: batchGetSubItemsByIdList
      description: get SubItems by id list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdListRequestBody'
      responses:
        '200':
          description: Successfully return a list of SubItems
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubItem'
components:
  schemas:
    ItemType:
      type: string
      enum:
        - anime
        - game
        - music
        - book
        - individual
        - character
        - real
        - association
        - corporation
        - organization
        - ship
        - mechanic
      x-enum-varnames:
        - Anime
        - Game
        - Music
        - Book
        - Individual
        - Character
        - RealWorld
        - Association
        - Corporation
        - Organization
        - Ship
        - Mechanic
    ItemSubType:
      type: string
      enum:
        - other
        - TV
        - web
        - OVA
        - movie
        - Novel
        - Comic
        - Illustration
        - jp
        - en
        - cn
        - PC
        - NDS
        - PSP
        - PS2
        - PS3
        - Xbox360
        - Mac OS
        - PS5
        - Xbox Series X/S
        - PS4
        - Xbox One
        - Nintendo Switch
        - Wii U
        - Wii
        - PS Vita
        - 3DS
        - iOS
        - Android
        - ARC
        - XBOX
        - GameCube
        - Dreamcast
        - Nitendo 64
        - PlayStation
        - SFC
        - FC
        - NEOGEO Pocket Color
        - GBA
        - GB
        - Virtual Boy
        - WonderSwan Color
        - WonderSwan
      x-enum-varnames:
        - Other
        - TV
        - Web
        - OVA
        - Movie
        - Novel
        - Comic
        - Illustration
        - DramaJp
        - DramaEn
        - DramaCn
        - PC
        - NDS
        - PSP
        - PS2
        - PS3
        - Xbox360
        - Mac
        - PS5
        - XboxSeriesXS
        - PS4
        - XboxOne
        - NintendoSwitch
        - WiiU
        - Wii
        - PSVita
        - N3DS
        - IOS
        - Android
        - ARC
        - XBOX
        - GameCube
        - Dreamcast
        - Nintendo64
        - PlayStation
        - SFC
        - FC
        - NEOGEOPocketColor
        - GBA
        - GB
        - VirtualBoy
        - WonderSwanColor
        - WonderSwan
    PropertyValue:
      title: PropertyValue
      type: object
      required:
        - 'value'
        - 'locked'
      properties:
        propertyType:
          type: string
          nullable: true
          enum:
            - Staff
            - Item
            - Character
            - Info
            - Cast
        locked:
          type: boolean
        value:
          oneOf:
            - type: string
            - type: array
              items:
                type: object
                additionalProperties:
                  type: string
            - type: array
              items:
                type: string
    OnAirItem:
      type: object
      required:
        - id
        - bgmId
        - type
      properties:
        id:
          type: string
        bgmId:
          type: integer
        publicTime:
          type: string
          description: RFC3339 Datetime
          format: date-time
          example: '2022-12-21T01:58:00Z'
        type:
          $ref: '#/components/schemas/ItemType'
        subType:
          $ref: '#/components/schemas/ItemSubType'
        name:
          type: string
        nameCn:
          type: string
        coverImage:
          $ref: '#/components/schemas/ImageInfo'
    ItemEntity:
      type: object
      required:
        - id
        - bgmId
        - properties
      properties:
        id:
          type: string
        bgmId:
          type: integer
        publicTime:
          type: string
          format: date-time
          description: Not used for ItemType.Individual and ItemType.Character
        name:
          type: string
        nameCn:
          type: string
        properties:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/PropertyValue'
    MainItem:
      allOf:
        - $ref: '#/components/schemas/ItemEntity'
        - type: object
          title: MainItem
          required:
            - mainType
            - type
            - isCollection
          properties:
            mainType:
              type: integer
              enum:
                - 0
                - 1
                - 2
              x-enum-varnames:
                - Item
                - Person
                - Character
            type:
              $ref: '#/components/schemas/ItemType'
            subType:
              $ref: '#/components/schemas/ItemSubType'
            isCollection:
              type: boolean
              description: determine if the MainItem is collection item
            coverImage:
              $ref: '#/components/schemas/ImageInfo'
            squareImage:
              $ref: '#/components/schemas/ImageInfo'
            subItems:
              type: array
              items:
                $ref: '#/components/schemas/SubItem'
            summary:
              type: string
    ImageInfo:
      title: ImageInfo
      type: object
      description: image information
      required:
        - id
        - url
        - width
        - height
        - dormantColor
      properties:
        id:
          type: string
        url:
          type: string
        width:
          type: integer
        height:
          type: integer
        dormantColor:
          type: string
    SubItem:
      allOf:
        - $ref: '#/components/schemas/ItemEntity'
        - type: object
          title: SubItem
          required:
            - type
            - episodeType
            - sort
            - mainItemId
          properties:
            type:
              type: integer
              enum:
                - 0
                - 1
              x-enum-varnames:
                - Episode
                - Song
            episodeType:
              type: integer
              nullable: true
              enum:
                - 0
                - 1
              x-enum-varnames:
                - Episode
                - Special
            ep:
              type: integer
              nullable: true
            disc:
              type: integer
              nullable: true
            desc:
              type: string
            sort:
              type: number
            mainItemId:
              type: string
            mainItem:
              $ref: '#/components/schemas/MainItem'
    IdListRequestBody:
      title: IdListRequestBody
      type: object
      required:
        - ids
      properties:
        ids:
          type: array
          items:
            type: string