//
// Announce.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Announce: Sendable, Codable, Hashable {

    public enum Position: Int, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case _1 = 1
        case _2 = 2
        case unknownDefaultOpenApi = 11184809
    }
    public var id: UUID
    public var content: String?
    public var imageUrl: String?
    /** 1=banner, 2=bangumi-specific. */
    public var position: Position
    public var sortOrder: Int?
    public var startTime: Date
    public var endTime: Date
    public var bangumi: BangumiSummary?

    public init(id: UUID, content: String? = nil, imageUrl: String? = nil, position: Position, sortOrder: Int? = nil, startTime: Date, endTime: Date, bangumi: BangumiSummary? = nil) {
        self.id = id
        self.content = content
        self.imageUrl = imageUrl
        self.position = position
        self.sortOrder = sortOrder
        self.startTime = startTime
        self.endTime = endTime
        self.bangumi = bangumi
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case content
        case imageUrl
        case position
        case sortOrder
        case startTime
        case endTime
        case bangumi
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encode(position, forKey: .position)
        try container.encodeIfPresent(sortOrder, forKey: .sortOrder)
        try container.encode(startTime, forKey: .startTime)
        try container.encode(endTime, forKey: .endTime)
        try container.encodeIfPresent(bangumi, forKey: .bangumi)
    }
}


extension Announce: Identifiable {}
