//
// FavoriteCheckNotFound.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FavoriteCheckNotFound: Sendable, Codable, Hashable {

    public var found: Bool

    public init(found: Bool) {
        self.found = found
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case found
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(found, forKey: .found)
    }
}

