//
// ItemPropertyValueValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ItemPropertyValueValue: Sendable, Codable, Hashable {
    case typeString(String)
    case typeArrayOfString([String])
    case typeArrayOfStringDictionary([[String: String]])

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeString(let value):
            try container.encode(value)
        case .typeArrayOfString(let value):
            try container.encode(value)
        case .typeArrayOfStringDictionary(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(String.self) {
            self = .typeString(value)
        } else if let value = try? container.decode([String].self) {
            self = .typeArrayOfString(value)
        } else if let value = try? container.decode([[String: String]].self) {
            self = .typeArrayOfStringDictionary(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of ItemPropertyValueValue"))
        }
    }
}

