//
// ItemTypeQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Enum key accepted by &#x60;GET /bangumi&#x60;. */
public enum ItemTypeQuery: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case anime = "Anime"
    case game = "Game"
    case music = "Music"
    case book = "Book"
    case individual = "Individual"
    case character = "Character"
    case realWorld = "RealWorld"
    case association = "Association"
    case corporation = "Corporation"
    case organization = "Organization"
    case ship = "Ship"
    case mechanic = "Mechanic"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
