//
// ItemPropertyValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ItemPropertyValue: Sendable, Codable, Hashable {

    public enum PropertyType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case staff = "Staff"
        case item = "Item"
        case character = "Character"
        case info = "Info"
        case cast = "Cast"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var value: ItemPropertyValueValue
    public var propertyType: PropertyType?
    public var locked: Bool

    public init(value: ItemPropertyValueValue, propertyType: PropertyType? = nil, locked: Bool) {
        self.value = value
        self.propertyType = propertyType
        self.locked = locked
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case propertyType
        case locked
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encodeIfPresent(propertyType, forKey: .propertyType)
        try container.encode(locked, forKey: .locked)
    }
}

