//
// ItemSubTypeQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Enum key accepted by &#x60;GET /bangumi&#x60;. */
public enum ItemSubTypeQuery: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case other = "Other"
    case tv = "TV"
    case web = "Web"
    case ova = "OVA"
    case movie = "Movie"
    case novel = "Novel"
    case manga = "Manga"
    case illustration = "Illustration"
    case dramaJp = "DramaJp"
    case dramaEn = "DramaEn"
    case dramaCn = "DramaCn"
    case pc = "PC"
    case nds = "NDS"
    case psp = "PSP"
    case ps2 = "PS2"
    case ps3 = "PS3"
    case xbox360 = "Xbox360"
    case mac = "Mac"
    case ps5 = "PS5"
    case xboxSeriesXS = "XboxSeriesXS"
    case ps4 = "PS4"
    case xboxOne = "XboxOne"
    case nintendoSwitch = "NintendoSwitch"
    case wiiU = "WiiU"
    case wii = "Wii"
    case psvita = "PSVita"
    case n3DS = "N3DS"
    case ios = "IOS"
    case android = "Android"
    case arc = "ARC"
    case xbox = "XBOX"
    case gameCube = "GameCube"
    case dreamcast = "Dreamcast"
    case nintendo64 = "Nintendo64"
    case playStation = "PlayStation"
    case sfc = "SFC"
    case fc = "FC"
    case neogeopocketcolor = "NEOGEOPocketColor"
    case gba = "GBA"
    case gb = "GB"
    case virtualBoy = "VirtualBoy"
    case wonderSwanColor = "WonderSwanColor"
    case wonderSwan = "WonderSwan"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
