//
// PaginatedFavorite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginatedFavorite: Sendable, Codable, Hashable {

    public static let totalRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var data: [FavoriteWithBangumi]
    public var total: Int

    public init(data: [FavoriteWithBangumi], total: Int) {
        self.data = data
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(total, forKey: .total)
    }
}

