//
// SubItemFavorite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SubItemFavorite: Sendable, Codable, Hashable {

    public var id: UUID
    public var subItem: IdReference

    public init(id: UUID, subItem: IdReference) {
        self.id = id
        self.subItem = subItem
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case subItem
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(subItem, forKey: .subItem)
    }
}


extension SubItemFavorite: Identifiable {}
