//
// AccountInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The authenticated account summary. Anonymous requests receive an empty object. */
public struct AccountInfo: Sendable, Codable, Hashable {

    public var id: UUID?
    public var subjectId: UUID?
    public var uid: UUID?
    public var role: String?

    public init(id: UUID? = nil, subjectId: UUID? = nil, uid: UUID? = nil, role: String? = nil) {
        self.id = id
        self.subjectId = subjectId
        self.uid = uid
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case subjectId
        case uid
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(subjectId, forKey: .subjectId)
        try container.encodeIfPresent(uid, forKey: .uid)
        try container.encodeIfPresent(role, forKey: .role)
    }
}


extension AccountInfo: Identifiable {}
