//
// BatchWatchProgressRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BatchWatchProgressRequest: Sendable, Codable, Hashable {

    public var records: [WatchHistoryRecord]

    public init(records: [WatchHistoryRecord]) {
        self.records = records
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case records
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(records, forKey: .records)
    }
}

