//
// BatchWatchProgressResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BatchWatchProgressResponse: Sendable, Codable, Hashable {

    public var changedFavorites: [FavoriteWithBangumi]

    public init(changedFavorites: [FavoriteWithBangumi]) {
        self.changedFavorites = changedFavorites
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case changedFavorites
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(changedFavorites, forKey: .changedFavorites)
    }
}

