//
// BrowserInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BrowserInfo: Sendable, Codable, Hashable {

    public var name: String
    public var version: String
    public var majorVersion: String
    public var webview: Bool
    public var chromium: Bool
    public var webkit: Bool

    public init(name: String, version: String, majorVersion: String, webview: Bool, chromium: Bool, webkit: Bool) {
        self.name = name
        self.version = version
        self.majorVersion = majorVersion
        self.webview = webview
        self.chromium = chromium
        self.webkit = webkit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case version
        case majorVersion
        case webview
        case chromium
        case webkit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(version, forKey: .version)
        try container.encode(majorVersion, forKey: .majorVersion)
        try container.encode(webview, forKey: .webview)
        try container.encode(chromium, forKey: .chromium)
        try container.encode(webkit, forKey: .webkit)
    }
}

