//
// EpisodeSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EpisodeSummary: Sendable, Codable, Hashable {

    public var id: UUID
    public var bgmEpsId: Int
    public var name: String?
    public var nameCn: String?
    public var airDate: OpenAPIDateWithoutTime?
    public var duration: String?
    public var type: EpisodeType?
    public var episodeNo: Int
    public var sort: Float
    public var subItemId: UUID?
    public var status: EpisodeStatus
    public var watchProgress: WatchProgressFields?
    public var thumbnailImage: Image?

    public init(id: UUID, bgmEpsId: Int, name: String? = nil, nameCn: String? = nil, airDate: OpenAPIDateWithoutTime? = nil, duration: String? = nil, type: EpisodeType? = nil, episodeNo: Int, sort: Float, subItemId: UUID? = nil, status: EpisodeStatus, watchProgress: WatchProgressFields?, thumbnailImage: Image?) {
        self.id = id
        self.bgmEpsId = bgmEpsId
        self.name = name
        self.nameCn = nameCn
        self.airDate = airDate
        self.duration = duration
        self.type = type
        self.episodeNo = episodeNo
        self.sort = sort
        self.subItemId = subItemId
        self.status = status
        self.watchProgress = watchProgress
        self.thumbnailImage = thumbnailImage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case bgmEpsId
        case name
        case nameCn
        case airDate
        case duration
        case type
        case episodeNo
        case sort
        case subItemId
        case status
        case watchProgress
        case thumbnailImage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(bgmEpsId, forKey: .bgmEpsId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(nameCn, forKey: .nameCn)
        try container.encodeIfPresent(airDate, forKey: .airDate)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(episodeNo, forKey: .episodeNo)
        try container.encode(sort, forKey: .sort)
        try container.encodeIfPresent(subItemId, forKey: .subItemId)
        try container.encode(status, forKey: .status)
        try container.encode(watchProgress, forKey: .watchProgress)
        try container.encode(thumbnailImage, forKey: .thumbnailImage)
    }
}


extension EpisodeSummary: Identifiable {}
