//
// EpisodeStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 0&#x3D;not downloaded, 1&#x3D;downloading, 2&#x3D;downloaded. */
public enum EpisodeStatus: Int, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case _0 = 0
    case _1 = 1
    case _2 = 2
    case unknownDefaultOpenApi = 11184809
}
