//
// FavoriteProgressRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FavoriteProgressRequest: Sendable, Codable, Hashable {

    public var subItemFavorites: [SubItemFavorite]
    public var bangumiId: UUID

    public init(subItemFavorites: [SubItemFavorite], bangumiId: UUID) {
        self.subItemFavorites = subItemFavorites
        self.bangumiId = bangumiId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subItemFavorites
        case bangumiId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subItemFavorites, forKey: .subItemFavorites)
        try container.encode(bangumiId, forKey: .bangumiId)
    }
}

