//
// FavoriteStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum FavoriteStatus: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case wish = "WISH"
    case watched = "WATCHED"
    case watching = "WATCHING"
    case pause = "PAUSE"
    case abandoned = "ABANDONED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
