//
// FavoriteSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FavoriteSummary: Sendable, Codable, Hashable {

    public var id: UUID
    public var userId: UUID
    public var status: FavoriteStatus
    public var updateTime: Date
    public var checkTime: Date
    public var itemId: UUID?
    public var externalFavoriteId: UUID?

    public init(id: UUID, userId: UUID, status: FavoriteStatus, updateTime: Date, checkTime: Date, itemId: UUID?, externalFavoriteId: UUID?) {
        self.id = id
        self.userId = userId
        self.status = status
        self.updateTime = updateTime
        self.checkTime = checkTime
        self.itemId = itemId
        self.externalFavoriteId = externalFavoriteId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userId
        case status
        case updateTime
        case checkTime
        case itemId
        case externalFavoriteId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(status, forKey: .status)
        try container.encode(updateTime, forKey: .updateTime)
        try container.encode(checkTime, forKey: .checkTime)
        try container.encode(itemId, forKey: .itemId)
        try container.encode(externalFavoriteId, forKey: .externalFavoriteId)
    }
}


extension FavoriteSummary: Identifiable {}
