//
// FavoriteCheckResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum FavoriteCheckResponse: Sendable, Codable, Hashable {
    case typeFavoriteCheckFound(FavoriteCheckFound)
    case typeFavoriteCheckNotFound(FavoriteCheckNotFound)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeFavoriteCheckFound(let value):
            try container.encode(value)
        case .typeFavoriteCheckNotFound(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(FavoriteCheckFound.self) {
            self = .typeFavoriteCheckFound(value)
        } else if let value = try? container.decode(FavoriteCheckNotFound.self) {
            self = .typeFavoriteCheckNotFound(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of FavoriteCheckResponse"))
        }
    }
}

