//
// FeedbackRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FeedbackRequest: Sendable, Codable, Hashable {

    public var deviceType: String
    public var os: String
    public var browser: BrowserInfo
    public var userAgent: String
    public var issue: String
    public var videoId: UUID

    public init(deviceType: String, os: String, browser: BrowserInfo, userAgent: String, issue: String, videoId: UUID) {
        self.deviceType = deviceType
        self.os = os
        self.browser = browser
        self.userAgent = userAgent
        self.issue = issue
        self.videoId = videoId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceType
        case os
        case browser
        case userAgent
        case issue
        case videoId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deviceType, forKey: .deviceType)
        try container.encode(os, forKey: .os)
        try container.encode(browser, forKey: .browser)
        try container.encode(userAgent, forKey: .userAgent)
        try container.encode(issue, forKey: .issue)
        try container.encode(videoId, forKey: .videoId)
    }
}

