//
// Message.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Message: Sendable, Codable, Hashable {

    public var id: UUID
    public var threadId: String?
    public var threadTitle: String?
    public var threadType: ThreadType
    public var content: String
    public var contentType: MessageContentType
    public var renderedContent: String?
    public var read: Bool
    public var createdTime: Date
    public var updatedTime: Date?
    public var recipient: IdReference?
    public var sender: IdReference?

    public init(id: UUID, threadId: String? = nil, threadTitle: String? = nil, threadType: ThreadType, content: String, contentType: MessageContentType, renderedContent: String? = nil, read: Bool, createdTime: Date, updatedTime: Date? = nil, recipient: IdReference? = nil, sender: IdReference? = nil) {
        self.id = id
        self.threadId = threadId
        self.threadTitle = threadTitle
        self.threadType = threadType
        self.content = content
        self.contentType = contentType
        self.renderedContent = renderedContent
        self.read = read
        self.createdTime = createdTime
        self.updatedTime = updatedTime
        self.recipient = recipient
        self.sender = sender
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case threadId
        case threadTitle
        case threadType
        case content
        case contentType
        case renderedContent
        case read
        case createdTime
        case updatedTime
        case recipient
        case sender
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(threadId, forKey: .threadId)
        try container.encodeIfPresent(threadTitle, forKey: .threadTitle)
        try container.encode(threadType, forKey: .threadType)
        try container.encode(content, forKey: .content)
        try container.encode(contentType, forKey: .contentType)
        try container.encodeIfPresent(renderedContent, forKey: .renderedContent)
        try container.encode(read, forKey: .read)
        try container.encode(createdTime, forKey: .createdTime)
        try container.encodeIfPresent(updatedTime, forKey: .updatedTime)
        try container.encodeIfPresent(recipient, forKey: .recipient)
        try container.encodeIfPresent(sender, forKey: .sender)
    }
}


extension Message: Identifiable {}
