//
// MessageContentType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum MessageContentType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case text = "text"
    case html = "html"
    case markdown = "markdown"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
