//
// OnAirBangumi.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OnAirBangumi: Sendable, Codable, Hashable {

    public enum ModelType: Int, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case _2 = 2
        case _6 = 6
        case unknownDefaultOpenApi = 11184809
    }
    public var id: UUID
    public var bgmId: Int
    public var name: String
    public var nameCn: String
    public var airDate: OpenAPIDateWithoutTime
    /** Numeric database type; 2=anime and 6=real-world. */
    public var type: ModelType
    public var subType: String?
    public var coverImage: Image?

    public init(id: UUID, bgmId: Int, name: String, nameCn: String, airDate: OpenAPIDateWithoutTime, type: ModelType, subType: String?, coverImage: Image?) {
        self.id = id
        self.bgmId = bgmId
        self.name = name
        self.nameCn = nameCn
        self.airDate = airDate
        self.type = type
        self.subType = subType
        self.coverImage = coverImage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case bgmId
        case name
        case nameCn
        case airDate
        case type
        case subType
        case coverImage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(bgmId, forKey: .bgmId)
        try container.encode(name, forKey: .name)
        try container.encode(nameCn, forKey: .nameCn)
        try container.encode(airDate, forKey: .airDate)
        try container.encode(type, forKey: .type)
        try container.encode(subType, forKey: .subType)
        try container.encode(coverImage, forKey: .coverImage)
    }
}


extension OnAirBangumi: Identifiable {}
