//
// ThreadType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ThreadType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case ticket = "Ticket"
    case message = "Message"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
