//
// WatchProgressStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 1&#x3D;WISH, 2&#x3D;WATCHED, 3&#x3D;WATCHING, 4&#x3D;PAUSE, 5&#x3D;ABANDONED. */
public enum WatchProgressStatus: Int, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case _1 = 1
    case _2 = 2
    case _3 = 3
    case _4 = 4
    case _5 = 5
    case unknownDefaultOpenApi = 11184809
}
