//
// WatchProgressUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WatchProgressUpdateRequest: Sendable, Codable, Hashable {

    public var episode: IdReference
    public var bangumi: IdReference
    public var watchStatus: WatchProgressStatus
    public var lastWatchPosition: Double?
    public var lastWatchTime: Date?
    public var percentage: Double?

    public init(episode: IdReference, bangumi: IdReference, watchStatus: WatchProgressStatus, lastWatchPosition: Double? = nil, lastWatchTime: Date? = nil, percentage: Double? = nil) {
        self.episode = episode
        self.bangumi = bangumi
        self.watchStatus = watchStatus
        self.lastWatchPosition = lastWatchPosition
        self.lastWatchTime = lastWatchTime
        self.percentage = percentage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case episode
        case bangumi
        case watchStatus
        case lastWatchPosition
        case lastWatchTime
        case percentage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(episode, forKey: .episode)
        try container.encode(bangumi, forKey: .bangumi)
        try container.encode(watchStatus, forKey: .watchStatus)
        try container.encodeIfPresent(lastWatchPosition, forKey: .lastWatchPosition)
        try container.encodeIfPresent(lastWatchTime, forKey: .lastWatchTime)
        try container.encodeIfPresent(percentage, forKey: .percentage)
    }
}

