//
// WatchProgressHistory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WatchProgressHistory: Sendable, Codable, Hashable {

    public var id: UUID
    public var userId: UUID
    public var watchStatus: WatchProgressStatus
    public var lastWatchPosition: Double?
    public var lastWatchTime: Date?
    public var percentage: Double?
    public var subItemId: UUID?
    public var externalSubItemFavoriteId: UUID?
    public var episode: EpisodeSummary
    public var bangumi: BangumiSummary

    public init(id: UUID, userId: UUID, watchStatus: WatchProgressStatus, lastWatchPosition: Double? = nil, lastWatchTime: Date? = nil, percentage: Double? = nil, subItemId: UUID? = nil, externalSubItemFavoriteId: UUID? = nil, episode: EpisodeSummary, bangumi: BangumiSummary) {
        self.id = id
        self.userId = userId
        self.watchStatus = watchStatus
        self.lastWatchPosition = lastWatchPosition
        self.lastWatchTime = lastWatchTime
        self.percentage = percentage
        self.subItemId = subItemId
        self.externalSubItemFavoriteId = externalSubItemFavoriteId
        self.episode = episode
        self.bangumi = bangumi
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userId
        case watchStatus
        case lastWatchPosition
        case lastWatchTime
        case percentage
        case subItemId
        case externalSubItemFavoriteId
        case episode
        case bangumi
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(watchStatus, forKey: .watchStatus)
        try container.encodeIfPresent(lastWatchPosition, forKey: .lastWatchPosition)
        try container.encodeIfPresent(lastWatchTime, forKey: .lastWatchTime)
        try container.encodeIfPresent(percentage, forKey: .percentage)
        try container.encodeIfPresent(subItemId, forKey: .subItemId)
        try container.encodeIfPresent(externalSubItemFavoriteId, forKey: .externalSubItemFavoriteId)
        try container.encode(episode, forKey: .episode)
        try container.encode(bangumi, forKey: .bangumi)
    }
}


extension WatchProgressHistory: Identifiable {}
