/**
 * mira Item API
 * Item API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GetMainItemListResponse } from '../model/models';


import { MiraConfiguration }                                     from '../configuration';



export interface DefaultMiraInterface {
    defaultHeaders: HttpHeaders;
    configuration: MiraConfiguration;

    /**
     * 
     * get a list of MainItem
     * @param sort can be asc or desc, default is desc
     * @param orderBy ordered by which field, default is createdTime
     * @param offset offset to start, default is 0
     * @param limit how many items returned per request, default is 20, maximum is 100
     */
    listMainItems(sort?: string, orderBy?: string, offset?: number, limit?: number, extraHttpRequestParams?: any): Observable<GetMainItemListResponse>;

}
