/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MainItem } from './mainItem';


export interface ClientMapping { 
    id: string;
    clientId: string;
    item: MainItem;
}

