/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeleteClientMappingByMainItemResponse { 
    /**
     * how many entries are deleted, 1 is successful, 0 is unsuccessful.
     */
    data: number;
}

