/**
 * mira Item API
 * Item API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EntityBase { 
    id: number;
    /**
     * RFC3339 Datetime
     */
    createdTime: string;
    /**
     * RFC3339 Datetime to set the updateTime
     */
    updateTime?: string;
    version: number;
    deleted: boolean;
}

