/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FavoriteStatus } from './favoriteStatus';
import { MainItem } from './mainItem';


export interface Favorite { 
    id: string;
    status: FavoriteStatus;
    item: MainItem;
    userId: string;
}
export namespace Favorite {
}


