/**
 * mira API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const FavoriteStatus = {
    Planned: 'Planned',
    Watched: 'Watched',
    Watching: 'Watching',
    OnHold: 'OnHold',
    Dropped: 'Dropped'
} as const;
export type FavoriteStatus = typeof FavoriteStatus[keyof typeof FavoriteStatus];

