/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FavoriteStatus = 'Planned' | 'Watched' | 'Watching' | 'OnHold' | 'Dropped';

export const FavoriteStatus = {
    Planned: 'Planned' as FavoriteStatus,
    Watched: 'Watched' as FavoriteStatus,
    Watching: 'Watching' as FavoriteStatus,
    OnHold: 'OnHold' as FavoriteStatus,
    Dropped: 'Dropped' as FavoriteStatus
};

