/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubItem } from './subItem';


export interface GetSubItemResponse { 
    data: SubItem;
    /**
     * result code, 0 is successful.
     */
    status: number;
}

