/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * image information
 */
export interface ImageInfo { 
    id: string;
    url: string;
    width: number;
    height: number;
    dormantColor: string;
}

