/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ItemType = 'anime' | 'game' | 'music' | 'book' | 'individual' | 'character' | 'real' | 'association' | 'corporation' | 'organization' | 'ship' | 'mechanic';

export const ItemType = {
    Anime: 'anime' as ItemType,
    Game: 'game' as ItemType,
    Music: 'music' as ItemType,
    Book: 'book' as ItemType,
    Individual: 'individual' as ItemType,
    Character: 'character' as ItemType,
    RealWorld: 'real' as ItemType,
    Association: 'association' as ItemType,
    Corporation: 'corporation' as ItemType,
    Organization: 'organization' as ItemType,
    Ship: 'ship' as ItemType,
    Mechanic: 'mechanic' as ItemType
};

