/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * represent the relation among the Item type, Person type and Character type MainItems, it can also only be Item and Character type relation.
 */
export interface ItemCastCharacterRelation { 
    id: string;
    mainItemId: string;
    mainItemBgmId: number;
    relatedCastId?: string | null;
    relatedCastBgmId: number | null;
    relatedCharacterId?: string | null;
    relatedCharacterBgmId: number;
    characterType: string;
    isLocked: boolean;
    relationType?: string;
}

