/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ItemSubType = 'other' | 'TV' | 'web' | 'OVA' | 'movie' | 'Novel' | 'Comic' | 'Illustration' | 'jp' | 'en' | 'cn' | 'PC' | 'NDS' | 'PSP' | 'PS2' | 'PS3' | 'Xbox360' | 'Mac OS' | 'PS5' | 'Xbox Series X/S' | 'PS4' | 'Xbox One' | 'Nintendo Switch' | 'Wii U' | 'Wii' | 'PS Vita' | '3DS' | 'iOS' | 'Android' | 'ARC' | 'XBOX' | 'GameCube' | 'Dreamcast' | 'Nitendo 64' | 'PlayStation' | 'SFC' | 'FC' | 'NEOGEO Pocket Color' | 'GBA' | 'GB' | 'Virtual Boy' | 'WonderSwan Color' | 'WonderSwan';

export const ItemSubType = {
    Other: 'other' as ItemSubType,
    TV: 'TV' as ItemSubType,
    Web: 'web' as ItemSubType,
    OVA: 'OVA' as ItemSubType,
    Movie: 'movie' as ItemSubType,
    Novel: 'Novel' as ItemSubType,
    Comic: 'Comic' as ItemSubType,
    Illustration: 'Illustration' as ItemSubType,
    DramaJp: 'jp' as ItemSubType,
    DramaEn: 'en' as ItemSubType,
    DramaCn: 'cn' as ItemSubType,
    PC: 'PC' as ItemSubType,
    NDS: 'NDS' as ItemSubType,
    PSP: 'PSP' as ItemSubType,
    PS2: 'PS2' as ItemSubType,
    PS3: 'PS3' as ItemSubType,
    Xbox360: 'Xbox360' as ItemSubType,
    Mac: 'Mac OS' as ItemSubType,
    PS5: 'PS5' as ItemSubType,
    XboxSeriesXS: 'Xbox Series X/S' as ItemSubType,
    PS4: 'PS4' as ItemSubType,
    XboxOne: 'Xbox One' as ItemSubType,
    NintendoSwitch: 'Nintendo Switch' as ItemSubType,
    WiiU: 'Wii U' as ItemSubType,
    Wii: 'Wii' as ItemSubType,
    PSVita: 'PS Vita' as ItemSubType,
    N3DS: '3DS' as ItemSubType,
    IOS: 'iOS' as ItemSubType,
    Android: 'Android' as ItemSubType,
    ARC: 'ARC' as ItemSubType,
    XBOX: 'XBOX' as ItemSubType,
    GameCube: 'GameCube' as ItemSubType,
    Dreamcast: 'Dreamcast' as ItemSubType,
    Nintendo64: 'Nitendo 64' as ItemSubType,
    PlayStation: 'PlayStation' as ItemSubType,
    SFC: 'SFC' as ItemSubType,
    FC: 'FC' as ItemSubType,
    NEOGEOPocketColor: 'NEOGEO Pocket Color' as ItemSubType,
    GBA: 'GBA' as ItemSubType,
    GB: 'GB' as ItemSubType,
    VirtualBoy: 'Virtual Boy' as ItemSubType,
    WonderSwanColor: 'WonderSwan Color' as ItemSubType,
    WonderSwan: 'WonderSwan' as ItemSubType
};

