/**
 * mira Item API
 * Item API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PropertyValue } from './propertyValue';


export interface ItemEntity { 
    id: string;
    /**
     * RFC3339 Datetime
     */
    createdTime: string;
    /**
     * RFC3339 Datetime to set the updateTime
     */
    updateTime?: string;
    version: number;
    deleted: boolean;
    bgmId: number;
    isBgmHide: boolean;
    lockedInBgm: boolean;
    /**
     * Not used for ItemType.Individual and ItemType.Character
     */
    publicTime?: string;
    /**
     * Not used for ItemType.Individual and ItemType.Character
     */
    isPublicTimeLocked: boolean;
    properties: { [key: string]: PropertyValue; };
    isCoverImageLocked: boolean;
}

