/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * represent the relation between the Item type MainItem and Person type MainItem
 */
export interface ItemPersonRelation { 
    id: string;
    mainItemId: string;
    mainItemBgmId: number;
    personItemId?: string | null;
    personItemBgmId: number;
    relationType: string;
    isLocked: boolean;
}

