/**
 * mira API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ItemType = {
    Anime: 'anime',
    Game: 'game',
    Music: 'music',
    Book: 'book',
    Individual: 'individual',
    Character: 'character',
    RealWorld: 'real',
    Association: 'association',
    Corporation: 'corporation',
    Organization: 'organization',
    Ship: 'ship',
    Mechanic: 'mechanic'
} as const;
export type ItemType = typeof ItemType[keyof typeof ItemType];

