/**
 * mira API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ItemSubType = {
    Other: 'other',
    TV: 'TV',
    Web: 'web',
    OVA: 'OVA',
    Movie: 'movie',
    Novel: 'Novel',
    Comic: 'Comic',
    Illustration: 'Illustration',
    DramaJp: 'jp',
    DramaEn: 'en',
    DramaCn: 'cn',
    PC: 'PC',
    NDS: 'NDS',
    PSP: 'PSP',
    PS2: 'PS2',
    PS3: 'PS3',
    Xbox360: 'Xbox360',
    Mac: 'Mac OS',
    PS5: 'PS5',
    XboxSeriesXS: 'Xbox Series X/S',
    PS4: 'PS4',
    XboxOne: 'Xbox One',
    NintendoSwitch: 'Nintendo Switch',
    WiiU: 'Wii U',
    Wii: 'Wii',
    PSVita: 'PS Vita',
    N3DS: '3DS',
    IOS: 'iOS',
    Android: 'Android',
    ARC: 'ARC',
    XBOX: 'XBOX',
    GameCube: 'GameCube',
    Dreamcast: 'Dreamcast',
    Nintendo64: 'Nitendo 64',
    PlayStation: 'PlayStation',
    SFC: 'SFC',
    FC: 'FC',
    NEOGEOPocketColor: 'NEOGEO Pocket Color',
    GBA: 'GBA',
    GB: 'GB',
    VirtualBoy: 'Virtual Boy',
    WonderSwanColor: 'WonderSwan Color',
    WonderSwan: 'WonderSwan'
} as const;
export type ItemSubType = typeof ItemSubType[keyof typeof ItemSubType];

