/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * represent the relation of the Item type MainItems
 */
export interface ItemRelation { 
    id: string;
    mainItemId: string;
    mainItemBgmId: number;
    relatedItemId?: string | null;
    relatedBgmId: number;
    relationType: string;
    isLocked: boolean;
}

