/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubItemFavorite } from './subItemFavorite';


export interface ListSubItemFavoriteResponse { 
    data: Array<SubItemFavorite>;
    /**
     * total number of the result, if itemId is provided, this field will not available
     */
    total?: number;
}

