/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemSubType } from './itemSubType';
import { ItemType } from './itemType';
import { MainType } from './mainType';
import { ImageInfo } from './imageInfo';


export interface MainItemBasic { 
    id: string;
    bgmId: string;
    mainType: MainType;
    type: ItemType;
    subType: ItemSubType;
    /**
     * determine if the MainItem is collection item
     */
    isCollection: boolean;
    coverImage?: ImageInfo;
    squareImage?: ImageInfo;
    name?: string;
    nameCn?: string;
}
export namespace MainItemBasic {
}


