/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MainType = 0 | 1 | 2;

export const MainType = {
    Item: 0 as MainType,
    Person: 1 as MainType,
    Character: 2 as MainType
};

