/**
 * mira Item API
 * Item API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubItem } from './subItem';
import { PropertyValue } from './propertyValue';
import { ImageInfo } from './imageInfo';


export interface MainItem { 
    id: number;
    /**
     * RFC3339 Datetime
     */
    createdTime: string;
    /**
     * RFC3339 Datetime to set the updateTime
     */
    updateTime?: string;
    version: number;
    deleted: boolean;
    bgmId: number;
    isBgmHide: boolean;
    lockedInBgm: boolean;
    /**
     * Not used for ItemType.Individual and ItemType.Character
     */
    publicTime?: string;
    /**
     * Not used for ItemType.Individual and ItemType.Character
     */
    isPublicTimeLocked: boolean;
    properties: { [key: string]: PropertyValue; };
    isCoverImageLocked: boolean;
    mainType: MainItem.MainTypeEnum;
    type: MainItem.TypeEnum;
    subType?: MainItem.SubTypeEnum;
    /**
     * determine if the MainItem is collection item
     */
    isCollection: boolean;
    coverImage?: ImageInfo;
    subItem?: Array<SubItem>;
}
export namespace MainItem {
    export type MainTypeEnum = 0 | 1 | 2;
    export const MainTypeEnum = {
        Item: 0 as MainTypeEnum,
        Person: 1 as MainTypeEnum,
        Character: 2 as MainTypeEnum
    };
    export type TypeEnum = 'anime' | 'game' | 'music' | 'book' | 'individual' | 'character' | 'real' | 'association' | 'corporation' | 'organization' | 'ship' | 'mechanic';
    export const TypeEnum = {
        Anime: 'anime' as TypeEnum,
        Game: 'game' as TypeEnum,
        Music: 'music' as TypeEnum,
        Book: 'book' as TypeEnum,
        Individual: 'individual' as TypeEnum,
        Character: 'character' as TypeEnum,
        RealWorld: 'real' as TypeEnum,
        Association: 'association' as TypeEnum,
        Corporation: 'corporation' as TypeEnum,
        Organization: 'organization' as TypeEnum,
        Ship: 'ship' as TypeEnum,
        Mechanic: 'mechanic' as TypeEnum
    };
    export type SubTypeEnum = 'other' | 'TV' | 'web' | 'OVA' | 'movie' | 'Novel' | 'Comic' | 'Illustration' | 'jp' | 'en' | 'cn' | 'PC' | 'NDS' | 'PSP' | 'PS2' | 'PS3' | 'Xbox360' | 'Mac OS' | 'PS5' | 'Xbox Series X/S' | 'PS4' | 'Xbox One' | 'Nintendo Switch' | 'Wii U' | 'Wii' | 'PS Vita' | '3DS' | 'iOS' | 'Android' | 'ARC' | 'XBOX' | 'GameCube' | 'Dreamcast' | 'Nitendo 64' | 'PlayStation' | 'SFC' | 'FC' | 'NEOGEO Pocket Color' | 'GBA' | 'GB' | 'Virtual Boy' | 'WonderSwan Color' | 'WonderSwan';
    export const SubTypeEnum = {
        Other: 'other' as SubTypeEnum,
        TV: 'TV' as SubTypeEnum,
        Web: 'web' as SubTypeEnum,
        OVA: 'OVA' as SubTypeEnum,
        Movie: 'movie' as SubTypeEnum,
        Novel: 'Novel' as SubTypeEnum,
        Comic: 'Comic' as SubTypeEnum,
        Illustration: 'Illustration' as SubTypeEnum,
        DramaJp: 'jp' as SubTypeEnum,
        DramaEn: 'en' as SubTypeEnum,
        DramaCn: 'cn' as SubTypeEnum,
        PC: 'PC' as SubTypeEnum,
        NDS: 'NDS' as SubTypeEnum,
        PSP: 'PSP' as SubTypeEnum,
        PS2: 'PS2' as SubTypeEnum,
        PS3: 'PS3' as SubTypeEnum,
        Xbox360: 'Xbox360' as SubTypeEnum,
        Mac: 'Mac OS' as SubTypeEnum,
        PS5: 'PS5' as SubTypeEnum,
        XboxSeriesXS: 'Xbox Series X/S' as SubTypeEnum,
        PS4: 'PS4' as SubTypeEnum,
        XboxOne: 'Xbox One' as SubTypeEnum,
        NintendoSwitch: 'Nintendo Switch' as SubTypeEnum,
        WiiU: 'Wii U' as SubTypeEnum,
        Wii: 'Wii' as SubTypeEnum,
        PSVita: 'PS Vita' as SubTypeEnum,
        N3DS: '3DS' as SubTypeEnum,
        IOS: 'iOS' as SubTypeEnum,
        Android: 'Android' as SubTypeEnum,
        ARC: 'ARC' as SubTypeEnum,
        XBOX: 'XBOX' as SubTypeEnum,
        GameCube: 'GameCube' as SubTypeEnum,
        Dreamcast: 'Dreamcast' as SubTypeEnum,
        Nintendo64: 'Nitendo 64' as SubTypeEnum,
        PlayStation: 'PlayStation' as SubTypeEnum,
        SFC: 'SFC' as SubTypeEnum,
        FC: 'FC' as SubTypeEnum,
        NEOGEOPocketColor: 'NEOGEO Pocket Color' as SubTypeEnum,
        GBA: 'GBA' as SubTypeEnum,
        GB: 'GB' as SubTypeEnum,
        VirtualBoy: 'Virtual Boy' as SubTypeEnum,
        WonderSwanColor: 'WonderSwan Color' as SubTypeEnum,
        WonderSwan: 'WonderSwan' as SubTypeEnum
    };
}


