/**
 * mira API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemSubType } from './itemSubType';
import { ItemType } from './itemType';
import { SubItem } from './subItem';
import { PropertyValue } from './propertyValue';
import { MainType } from './mainType';
import { ImageInfo } from './imageInfo';


export interface MainItem { 
    id: string;
    bgmId: number;
    /**
     * Not used for ItemType.Individual and ItemType.Character
     */
    publicTime?: string;
    name?: string;
    nameCn?: string;
    properties: { [key: string]: PropertyValue; };
    mainType: MainType;
    type: ItemType;
    subType?: ItemSubType;
    /**
     * determine if the MainItem is collection item
     */
    isCollection: boolean;
    coverImage?: ImageInfo;
    squareImage?: ImageInfo;
    subItems?: Array<SubItem>;
    summary?: string;
}
export namespace MainItem {
}


