/**
 * mira API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const MainType = {
    Item: 0,
    Person: 1,
    Character: 2
} as const;
export type MainType = typeof MainType[keyof typeof MainType];

