/**
 * mira Item API
 * Item API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemSubType } from './itemSubType';
import { ItemType } from './itemType';
import { ImageInfo } from './imageInfo';


export interface OnAirItem { 
    id: number;
    bgmId: number;
    /**
     * RFC3339 Datetime
     */
    publicTime?: string;
    type: ItemType;
    subType?: ItemSubType;
    name?: string;
    name_cn?: string;
    coverImage?: ImageInfo;
}
export namespace OnAirItem {
}


