/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FavoriteStatus } from './favoriteStatus';


export interface PatchFavoriteBody { 
    status: FavoriteStatus;
    reviewComment?: string;
    rating?: number;
}
export namespace PatchFavoriteBody {
}


