/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MainItemBasic } from './mainItemBasic';
import { ItemPersonRelation } from './itemPersonRelation';
import { ItemCastCharacterRelation } from './itemCastCharacterRelation';


export interface PersonRelationsWithMainItems { 
    mainItems: Array<MainItemBasic>;
    relatedItems: Array<ItemPersonRelation>;
    relatedCharacters: Array<ItemCastCharacterRelation>;
}

