/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemPersonRelation } from './itemPersonRelation';
import { ItemCastCharacterRelation } from './itemCastCharacterRelation';
import { MainItem } from './mainItem';


export interface PersonRelationsWithMainItems { 
    mainItems: Array<MainItem>;
    relatedItems: Array<ItemPersonRelation>;
    relatedCharacters: Array<ItemCastCharacterRelation>;
}

