/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PropertyType = 'Staff' | 'Item' | 'Character' | 'Info' | 'Cast';

export const PropertyType = {
    Staff: 'Staff' as PropertyType,
    Item: 'Item' as PropertyType,
    Character: 'Character' as PropertyType,
    Info: 'Info' as PropertyType,
    Cast: 'Cast' as PropertyType
};

