/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * @type PropertyValueValue
 * @export
 */
export type PropertyValueValue = Array<string> | Array<{ [key: string]: string; }> | string;

