/**
 * mira API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PropertyType = {
    Staff: 'Staff',
    Item: 'Item',
    Character: 'Character',
    Info: 'Info',
    Cast: 'Cast'
} as const;
export type PropertyType = typeof PropertyType[keyof typeof PropertyType];

