/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PropertyValueValue } from './propertyValueValue';
import { PropertyType } from './propertyType';


export interface PropertyValue { 
    anidbKey?: string;
    bgmKey?: string;
    propertyType?: PropertyType;
    locked: boolean;
    value: PropertyValueValue;
}
export namespace PropertyValue {
}


