/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PropertyValueValue } from './propertyValueValue';


export interface PropertyValue { 
    propertyType?: PropertyValue.PropertyTypeEnum | null;
    locked: boolean;
    value: PropertyValueValue;
}
export namespace PropertyValue {
    export type PropertyTypeEnum = 'Staff' | 'Item' | 'Character' | 'Info' | 'Cast';
    export const PropertyTypeEnum = {
        Staff: 'Staff' as PropertyTypeEnum,
        Item: 'Item' as PropertyTypeEnum,
        Character: 'Character' as PropertyTypeEnum,
        Info: 'Info' as PropertyTypeEnum,
        Cast: 'Cast' as PropertyTypeEnum
    };
}


