/**
 * mira Item API
 * Item API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PropertyValue } from './propertyValue';


export interface SubItem { 
    id: string;
    /**
     * RFC3339 Datetime
     */
    createdTime: string;
    /**
     * RFC3339 Datetime to set the updateTime
     */
    updateTime?: string;
    version: number;
    deleted: boolean;
    bgmId: number;
    isBgmHide: boolean;
    lockedInBgm: boolean;
    /**
     * Not used for ItemType.Individual and ItemType.Character
     */
    publicTime?: string;
    /**
     * Not used for ItemType.Individual and ItemType.Character
     */
    isPublicTimeLocked: boolean;
    properties: { [key: string]: PropertyValue; };
    isCoverImageLocked: boolean;
    type: SubItem.TypeEnum;
    episodeType: SubItem.EpisodeTypeEnum | null;
    ep?: number | null;
    disc?: number | null;
    sort: number;
}
export namespace SubItem {
    export type TypeEnum = 0 | 1;
    export const TypeEnum = {
        Episode: 0 as TypeEnum,
        Song: 1 as TypeEnum
    };
    export type EpisodeTypeEnum = 0 | 1;
    export const EpisodeTypeEnum = {
        Episode: 0 as EpisodeTypeEnum,
        Special: 1 as EpisodeTypeEnum
    };
}


