/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubItem } from './subItem';


export interface SubItemFavorite { 
    id: string;
    /**
     * RFC3339 Datetime
     */
    createdTime: string;
    /**
     * RFC3339 Datetime to set the updateTime
     */
    updateTime?: string;
    version: number;
    deleted: boolean;
    subItem: SubItem;
    userId: string;
}

