/**
 * mira API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Favorite } from './favorite';
import { SubItemFavorite } from './subItemFavorite';


export interface SyncFavoritesResponse { 
    favorites?: Array<Favorite>;
    subItemFavorites?: Array<SubItemFavorite>;
    deletedItemIds?: Array<string>;
    deletedSubItemIds?: Array<string>;
}

