/**
 * mira API
 * API for Project-Mira
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SyncFavoritesRequestBodyFavoritesInner } from './syncFavoritesRequestBodyFavoritesInner';


export interface SyncFavoritesRequestBody { 
    favorites: Array<SyncFavoritesRequestBodyFavoritesInner>;
    acceptSideOnMerge: SyncFavoritesRequestBody.AcceptSideOnMergeEnum;
}
export namespace SyncFavoritesRequestBody {
    export type AcceptSideOnMergeEnum = 'incoming' | 'local';
    export const AcceptSideOnMergeEnum = {
        Incoming: 'incoming' as AcceptSideOnMergeEnum,
        Local: 'local' as AcceptSideOnMergeEnum
    };
}


