//
// BangumiSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BangumiSummary: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case anime = "anime"
        case game = "game"
        case music = "music"
        case book = "book"
        case real = "real"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let airWeekdayRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 6, exclusiveMaximum: false, multipleOf: nil)
    public var id: UUID
    public var bgmId: Int
    public var name: String
    public var nameCn: String
    public var summary: String
    public var coverImage: Image
    public var airDate: OpenAPIDateWithoutTime
    public var airWeekday: Int?
    public var type: ModelType?
    public var subType: String?
    public var itemId: UUID?

    public init(id: UUID, bgmId: Int, name: String, nameCn: String, summary: String, coverImage: Image, airDate: OpenAPIDateWithoutTime, airWeekday: Int?, type: ModelType?, subType: String?, itemId: UUID?) {
        self.id = id
        self.bgmId = bgmId
        self.name = name
        self.nameCn = nameCn
        self.summary = summary
        self.coverImage = coverImage
        self.airDate = airDate
        self.airWeekday = airWeekday
        self.type = type
        self.subType = subType
        self.itemId = itemId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case bgmId
        case name
        case nameCn
        case summary
        case coverImage
        case airDate
        case airWeekday
        case type
        case subType
        case itemId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(bgmId, forKey: .bgmId)
        try container.encode(name, forKey: .name)
        try container.encode(nameCn, forKey: .nameCn)
        try container.encode(summary, forKey: .summary)
        try container.encode(coverImage, forKey: .coverImage)
        try container.encode(airDate, forKey: .airDate)
        try container.encode(airWeekday, forKey: .airWeekday)
        try container.encode(type, forKey: .type)
        try container.encode(subType, forKey: .subType)
        try container.encode(itemId, forKey: .itemId)
    }
}


extension BangumiSummary: Identifiable {}
