//
// EpisodeType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** 0&#x3D;Episode, 1&#x3D;Special. */
public enum EpisodeType: Int, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case _0 = 0
    case _1 = 1
    case unknownDefaultOpenApi = 11184809
}
