//
// FavoriteCheckFound.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FavoriteCheckFound: Sendable, Codable, Hashable {

    public var found: Bool
    public var checkTime: Date

    public init(found: Bool, checkTime: Date) {
        self.found = found
        self.checkTime = checkTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case found
        case checkTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(found, forKey: .found)
        try container.encode(checkTime, forKey: .checkTime)
    }
}

