//
// FavoriteCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FavoriteCreateRequest: Sendable, Codable, Hashable {

    public var status: FavoriteStatus
    public var bangumiId: UUID
    public var review: String?
    public var rating: Double?
    public var syncToUpstream: Bool? = false

    public init(status: FavoriteStatus, bangumiId: UUID, review: String? = nil, rating: Double? = nil, syncToUpstream: Bool? = false) {
        self.status = status
        self.bangumiId = bangumiId
        self.review = review
        self.rating = rating
        self.syncToUpstream = syncToUpstream
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case bangumiId
        case review
        case rating
        case syncToUpstream
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(bangumiId, forKey: .bangumiId)
        try container.encodeIfPresent(review, forKey: .review)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(syncToUpstream, forKey: .syncToUpstream)
    }
}

