//
// Image.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Image: Sendable, Codable, Hashable {

    public var id: UUID
    public var width: Int?
    public var height: Int?
    public var dominantColor: String?
    /** Public image URL, or an empty string when no source is available. */
    public var url: String

    public init(id: UUID, width: Int? = nil, height: Int? = nil, dominantColor: String? = nil, url: String) {
        self.id = id
        self.width = width
        self.height = height
        self.dominantColor = dominantColor
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case width
        case height
        case dominantColor
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(dominantColor, forKey: .dominantColor)
        try container.encode(url, forKey: .url)
    }
}


extension Image: Identifiable {}
