//
// VideoFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoFile: Sendable, Codable, Hashable {

    public var id: UUID
    public var bangumi: IdReference
    public var episode: IdReference
    public var url: String
    public var fileName: String?
    public var resolutionW: Int?
    public var resolutionH: Int?
    public var duration: Double?
    public var label: String?
    public var kfTileSize: Int?
    public var kfFrameWidth: Int?
    public var kfFrameHeight: Int?
    public var kfImagePathList: [String]?

    public init(id: UUID, bangumi: IdReference, episode: IdReference, url: String, fileName: String? = nil, resolutionW: Int? = nil, resolutionH: Int? = nil, duration: Double? = nil, label: String? = nil, kfTileSize: Int? = nil, kfFrameWidth: Int? = nil, kfFrameHeight: Int? = nil, kfImagePathList: [String]? = nil) {
        self.id = id
        self.bangumi = bangumi
        self.episode = episode
        self.url = url
        self.fileName = fileName
        self.resolutionW = resolutionW
        self.resolutionH = resolutionH
        self.duration = duration
        self.label = label
        self.kfTileSize = kfTileSize
        self.kfFrameWidth = kfFrameWidth
        self.kfFrameHeight = kfFrameHeight
        self.kfImagePathList = kfImagePathList
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case bangumi
        case episode
        case url
        case fileName
        case resolutionW
        case resolutionH
        case duration
        case label
        case kfTileSize
        case kfFrameWidth
        case kfFrameHeight
        case kfImagePathList
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(bangumi, forKey: .bangumi)
        try container.encode(episode, forKey: .episode)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(fileName, forKey: .fileName)
        try container.encodeIfPresent(resolutionW, forKey: .resolutionW)
        try container.encodeIfPresent(resolutionH, forKey: .resolutionH)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(kfTileSize, forKey: .kfTileSize)
        try container.encodeIfPresent(kfFrameWidth, forKey: .kfFrameWidth)
        try container.encodeIfPresent(kfFrameHeight, forKey: .kfFrameHeight)
        try container.encodeIfPresent(kfImagePathList, forKey: .kfImagePathList)
    }
}


extension VideoFile: Identifiable {}
