//
// WatchHistoryRecord.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WatchHistoryRecord: Sendable, Codable, Hashable {

    public var bangumiId: UUID
    public var episodeId: UUID
    public var lastWatchPosition: Double
    public var lastWatchTime: Date
    public var percentage: Double
    public var isFinished: Bool

    public init(bangumiId: UUID, episodeId: UUID, lastWatchPosition: Double, lastWatchTime: Date, percentage: Double, isFinished: Bool) {
        self.bangumiId = bangumiId
        self.episodeId = episodeId
        self.lastWatchPosition = lastWatchPosition
        self.lastWatchTime = lastWatchTime
        self.percentage = percentage
        self.isFinished = isFinished
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bangumiId
        case episodeId
        case lastWatchPosition
        case lastWatchTime
        case percentage
        case isFinished
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bangumiId, forKey: .bangumiId)
        try container.encode(episodeId, forKey: .episodeId)
        try container.encode(lastWatchPosition, forKey: .lastWatchPosition)
        try container.encode(lastWatchTime, forKey: .lastWatchTime)
        try container.encode(percentage, forKey: .percentage)
        try container.encode(isFinished, forKey: .isFinished)
    }
}

