//
// AnnounceAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AnnounceAPI {
    public let apiConfiguration: OpenAPIClientAPIConfiguration
    public init(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) {
        self.apiConfiguration = apiConfiguration
    }

    /**
     List currently available announcements
     
     - returns: [Announce]
     */
    open func listAnnouncements() async throws(ErrorResponse) -> [Announce] {
        return try await listAnnouncementsWithRequestBuilder().execute().body
    }

    /**
     List currently available announcements
     - GET /announce
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<[Announce]> 
     */
    open func listAnnouncementsWithRequestBuilder() -> RequestBuilder<[Announce]> {
        let localVariablePath = "/announce"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Announce]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
