//
// EpisodeAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class EpisodeAPI {
    public let apiConfiguration: OpenAPIClientAPIConfiguration
    public init(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) {
        self.apiConfiguration = apiConfiguration
    }

    /**
     Get an episode and its playable video files
     
     - parameter id: (path)  
     - parameter loadBangumiEpisodes: (query) Include the other episodes belonging to the same Bangumi. (optional, default to false)
     - parameter loadFavorite: (query) Include the current account&#39;s favorite on the nested Bangumi when one exists. (optional, default to false)
     - returns: EpisodeDetail
     */
    open func getEpisode(id: UUID, loadBangumiEpisodes: Bool? = nil, loadFavorite: Bool? = nil) async throws(ErrorResponse) -> EpisodeDetail {
        return try await getEpisodeWithRequestBuilder(id: id, loadBangumiEpisodes: loadBangumiEpisodes, loadFavorite: loadFavorite).execute().body
    }

    /**
     Get an episode and its playable video files
     - GET /episode/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter loadBangumiEpisodes: (query) Include the other episodes belonging to the same Bangumi. (optional, default to false)
     - parameter loadFavorite: (query) Include the current account&#39;s favorite on the nested Bangumi when one exists. (optional, default to false)
     - returns: RequestBuilder<EpisodeDetail> 
     */
    open func getEpisodeWithRequestBuilder(id: UUID, loadBangumiEpisodes: Bool? = nil, loadFavorite: Bool? = nil) -> RequestBuilder<EpisodeDetail> {
        var localVariablePath = "/episode/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "loadBangumiEpisodes": (wrappedValue: loadBangumiEpisodes?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "loadFavorite": (wrappedValue: loadFavorite?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EpisodeDetail>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List watch history
     
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query) Values outside 0 through 300 fall back to 20. (optional, default to 20)
     - returns: PaginatedWatchProgress
     */
    open func listWatchHistory(offset: Int? = nil, limit: Int? = nil) async throws(ErrorResponse) -> PaginatedWatchProgress {
        return try await listWatchHistoryWithRequestBuilder(offset: offset, limit: limit).execute().body
    }

    /**
     List watch history
     - GET /episode/watch/history
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query) Values outside 0 through 300 fall back to 20. (optional, default to 20)
     - returns: RequestBuilder<PaginatedWatchProgress> 
     */
    open func listWatchHistoryWithRequestBuilder(offset: Int? = nil, limit: Int? = nil) -> RequestBuilder<PaginatedWatchProgress> {
        let localVariablePath = "/episode/watch/history"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "offset": (wrappedValue: offset?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedWatchProgress>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Submit feedback for an episode
     
     - parameter episodeId: (path)  
     - parameter feedbackRequest: (body)  
     - returns: Void
     */
    open func submitEpisodeFeedback(episodeId: UUID, feedbackRequest: FeedbackRequest) async throws(ErrorResponse) {
        return try await submitEpisodeFeedbackWithRequestBuilder(episodeId: episodeId, feedbackRequest: feedbackRequest).execute().body
    }

    /**
     Submit feedback for an episode
     - POST /episode/feedback/{episodeId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter episodeId: (path)  
     - parameter feedbackRequest: (body)  
     - returns: RequestBuilder<Void> 
     */
    open func submitEpisodeFeedbackWithRequestBuilder(episodeId: UUID, feedbackRequest: FeedbackRequest) -> RequestBuilder<Void> {
        var localVariablePath = "/episode/feedback/{episodeId}"
        let episodeIdPreEscape = "\(APIHelper.mapValueToPathItem(episodeId))"
        let episodeIdPostEscape = episodeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{episodeId}", with: episodeIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: feedbackRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Synchronize a batch of watch-history records
     
     - parameter batchWatchProgressRequest: (body)  
     - parameter syncToUpstream: (query) Set to false to skip synchronization with the upstream Mira service. (optional, default to true)
     - returns: BatchWatchProgressResponse
     */
    open func syncWatchProgress(batchWatchProgressRequest: BatchWatchProgressRequest, syncToUpstream: Bool? = nil) async throws(ErrorResponse) -> BatchWatchProgressResponse {
        return try await syncWatchProgressWithRequestBuilder(batchWatchProgressRequest: batchWatchProgressRequest, syncToUpstream: syncToUpstream).execute().body
    }

    /**
     Synchronize a batch of watch-history records
     - POST /episode/watch/sync
     - Invalid records are ignored. When no valid records remain, the current implementation returns 200 without a response body; normal success returns `changedFavorites`.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter batchWatchProgressRequest: (body)  
     - parameter syncToUpstream: (query) Set to false to skip synchronization with the upstream Mira service. (optional, default to true)
     - returns: RequestBuilder<BatchWatchProgressResponse> 
     */
    open func syncWatchProgressWithRequestBuilder(batchWatchProgressRequest: BatchWatchProgressRequest, syncToUpstream: Bool? = nil) -> RequestBuilder<BatchWatchProgressResponse> {
        let localVariablePath = "/episode/watch/sync"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: batchWatchProgressRequest, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "syncToUpstream": (wrappedValue: syncToUpstream?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BatchWatchProgressResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create or update watch progress
     
     - parameter watchProgressUpdateRequest: (body)  
     - parameter syncToUpstream: (query) Set to false to skip synchronization with the upstream Mira service. (optional, default to true)
     - returns: WatchProgressSummary
     */
    open func updateWatchProgress(watchProgressUpdateRequest: WatchProgressUpdateRequest, syncToUpstream: Bool? = nil) async throws(ErrorResponse) -> WatchProgressSummary {
        return try await updateWatchProgressWithRequestBuilder(watchProgressUpdateRequest: watchProgressUpdateRequest, syncToUpstream: syncToUpstream).execute().body
    }

    /**
     Create or update watch progress
     - POST /episode/watch
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter watchProgressUpdateRequest: (body)  
     - parameter syncToUpstream: (query) Set to false to skip synchronization with the upstream Mira service. (optional, default to true)
     - returns: RequestBuilder<WatchProgressSummary> 
     */
    open func updateWatchProgressWithRequestBuilder(watchProgressUpdateRequest: WatchProgressUpdateRequest, syncToUpstream: Bool? = nil) -> RequestBuilder<WatchProgressSummary> {
        let localVariablePath = "/episode/watch"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: watchProgressUpdateRequest, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "syncToUpstream": (wrappedValue: syncToUpstream?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<WatchProgressSummary>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
