/* tslint:disable */
/* eslint-disable */
/**
 * mira API
 * API for Project-Mira
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    BatchGetMainItemByIdListResult,
    BatchGetSubItemByIdListResult,
    CharacterRelationsWithMainItems,
    ClientMapping,
    CreateSubItemFavoriteResponse,
    CreateSubItemFavoritesRequestBody,
    DeleteClientMappingByMainItemResponse,
    Favorite,
    FavoriteProgress,
    GetFavoriteResponse,
    GetOnAirItemListResponse,
    IdListRequestBody,
    ItemRelationsWithMainItems,
    ListFavoritesResponse,
    ListMainItemResponse,
    ListSubItemFavoriteResponse,
    MainItem,
    PatchFavoriteBody,
    PersonRelationsWithMainItems,
    SubItem,
    SucceedEmptyResponse,
    SyncFavoritesRequestBody,
    SyncFavoritesResponse,
    SyncSubItemFavoritesByFavoriteIdRequestBody,
    SyncSubItemFavoritesByFavoriteIdResponse,
} from '../models/index';

export interface AddClientMappingRequest {
    request_body: Array<string>;
}

export interface BatchGetMainItemByIdListRequest {
    IdListRequestBody: IdListRequestBody;
}

export interface BatchGetSubItemsByIdListRequest {
    IdListRequestBody: IdListRequestBody;
}

export interface CreateFavoriteRequest {
    Favorite: Omit<Favorite, 'id'>;
}

export interface CreateSubItemFavoritesRequest {
    CreateSubItemFavoritesRequestBody: CreateSubItemFavoritesRequestBody;
}

export interface DeleteClientMappingByMainItemIdRequest {
    id: string;
}

export interface DeleteFavoriteRequest {
    id: string;
}

export interface DeleteSubItemFavoriteRequest {
    id: string;
}

export interface GetFavoriteByIdRequest {
    id: string;
}

export interface GetFavoriteByMainItemIdRequest {
    id: string;
}

export interface GetFavoriteProgressByMainItemIdRequest {
    mainItemId: string;
    epType: number;
}

export interface GetMainItemByIdRequest {
    id: string;
    coverImage?: string;
    subItems?: string;
}

export interface GetRelationsOfCharacterRequest {
    id: string;
}

export interface GetRelationsOfItemRequest {
    id: string;
}

export interface GetRelationsOfPersonRequest {
    id: string;
}

export interface GetSubItemByIdRequest {
    id: string;
}

export interface ListFavoritesRequest {
    status: string;
    offset?: number;
    limit?: number;
    orderBy?: string;
    sort?: string;
}

export interface ListMainItemsRequest {
    serviceClientId?: string;
    mainType?: string;
    type?: string;
    subType?: string;
    offset?: number;
    limit?: number;
    orderBy?: string;
    sort?: string;
    keyword?: string;
}

export interface ListSubItemFavoritesRequest {
    itemId?: string;
    offset?: number;
    limit?: number;
    orderBy?: string;
    sort?: string;
    subItem?: boolean;
}

export interface OnAirItemRequest {
    type: string;
}

export interface PatchFavoriteRequest {
    id: string;
    PatchFavoriteBody: PatchFavoriteBody;
}

export interface PredictMainItemNameRequest {
    prefix: string;
}

export interface SyncFavoritesRequest {
    SyncFavoritesRequestBody: SyncFavoritesRequestBody;
}

export interface SyncSubItemFavoritesByFavoriteIdRequest {
    favoriteId: string;
    SyncSubItemFavoritesByFavoriteIdRequestBody: SyncSubItemFavoritesByFavoriteIdRequestBody;
}

export interface UpdateFavoriteProgressRequest {
    mainItemId: string;
    progress: number;
    epType: number;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * Creates request options for addClientMapping without sending the request
     * @param {Array<string>} request_body 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    addClientMappingRequestOpts(requestParameters: AddClientMappingRequest): Promise<runtime.RequestOpts>;

    /**
     * Add ClientMapping
     * @param {Array<string>} request_body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    addClientMappingRaw(requestParameters: AddClientMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClientMapping>>;

    /**
     * Add ClientMapping
     */
    addClientMapping(requestParameters: AddClientMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClientMapping>;

    /**
     * Creates request options for batchGetMainItemByIdList without sending the request
     * @param {IdListRequestBody} IdListRequestBody 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    batchGetMainItemByIdListRequestOpts(requestParameters: BatchGetMainItemByIdListRequest): Promise<runtime.RequestOpts>;

    /**
     * get mainItems by id list
     * @param {IdListRequestBody} IdListRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    batchGetMainItemByIdListRaw(requestParameters: BatchGetMainItemByIdListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchGetMainItemByIdListResult>>;

    /**
     * get mainItems by id list
     */
    batchGetMainItemByIdList(requestParameters: BatchGetMainItemByIdListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchGetMainItemByIdListResult>;

    /**
     * Creates request options for batchGetSubItemsByIdList without sending the request
     * @param {IdListRequestBody} IdListRequestBody 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    batchGetSubItemsByIdListRequestOpts(requestParameters: BatchGetSubItemsByIdListRequest): Promise<runtime.RequestOpts>;

    /**
     * get SubItems by id list
     * @param {IdListRequestBody} IdListRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    batchGetSubItemsByIdListRaw(requestParameters: BatchGetSubItemsByIdListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchGetSubItemByIdListResult>>;

    /**
     * get SubItems by id list
     */
    batchGetSubItemsByIdList(requestParameters: BatchGetSubItemsByIdListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchGetSubItemByIdListResult>;

    /**
     * Creates request options for createFavorite without sending the request
     * @param {Favorite} Favorite 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createFavoriteRequestOpts(requestParameters: CreateFavoriteRequest): Promise<runtime.RequestOpts>;

    /**
     * create a favorite for user and item
     * @param {Favorite} Favorite 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createFavoriteRaw(requestParameters: CreateFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Favorite>>;

    /**
     * create a favorite for user and item
     */
    createFavorite(requestParameters: CreateFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Favorite>;

    /**
     * Creates request options for createSubItemFavorites without sending the request
     * @param {CreateSubItemFavoritesRequestBody} CreateSubItemFavoritesRequestBody 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createSubItemFavoritesRequestOpts(requestParameters: CreateSubItemFavoritesRequest): Promise<runtime.RequestOpts>;

    /**
     * create SubItemFavorites
     * @param {CreateSubItemFavoritesRequestBody} CreateSubItemFavoritesRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createSubItemFavoritesRaw(requestParameters: CreateSubItemFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSubItemFavoriteResponse>>;

    /**
     * create SubItemFavorites
     */
    createSubItemFavorites(requestParameters: CreateSubItemFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSubItemFavoriteResponse>;

    /**
     * Creates request options for deleteClientMappingByMainItemId without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteClientMappingByMainItemIdRequestOpts(requestParameters: DeleteClientMappingByMainItemIdRequest): Promise<runtime.RequestOpts>;

    /**
     * Delete ClientMapping by MainItem id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteClientMappingByMainItemIdRaw(requestParameters: DeleteClientMappingByMainItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteClientMappingByMainItemResponse>>;

    /**
     * Delete ClientMapping by MainItem id
     */
    deleteClientMappingByMainItemId(requestParameters: DeleteClientMappingByMainItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteClientMappingByMainItemResponse>;

    /**
     * Creates request options for deleteFavorite without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteFavoriteRequestOpts(requestParameters: DeleteFavoriteRequest): Promise<runtime.RequestOpts>;

    /**
     * Delete a favorite
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteFavoriteRaw(requestParameters: DeleteFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucceedEmptyResponse>>;

    /**
     * Delete a favorite
     */
    deleteFavorite(requestParameters: DeleteFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucceedEmptyResponse>;

    /**
     * Creates request options for deleteSubItemFavorite without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteSubItemFavoriteRequestOpts(requestParameters: DeleteSubItemFavoriteRequest): Promise<runtime.RequestOpts>;

    /**
     * Delete a SubItemFavorite
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteSubItemFavoriteRaw(requestParameters: DeleteSubItemFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucceedEmptyResponse>>;

    /**
     * Delete a SubItemFavorite
     */
    deleteSubItemFavorite(requestParameters: DeleteSubItemFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucceedEmptyResponse>;

    /**
     * Creates request options for getFavoriteById without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getFavoriteByIdRequestOpts(requestParameters: GetFavoriteByIdRequest): Promise<runtime.RequestOpts>;

    /**
     * Get a favorite by id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getFavoriteByIdRaw(requestParameters: GetFavoriteByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetFavoriteResponse>>;

    /**
     * Get a favorite by id
     */
    getFavoriteById(requestParameters: GetFavoriteByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetFavoriteResponse>;

    /**
     * Creates request options for getFavoriteByMainItemId without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getFavoriteByMainItemIdRequestOpts(requestParameters: GetFavoriteByMainItemIdRequest): Promise<runtime.RequestOpts>;

    /**
     * get favorite by MainItem id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getFavoriteByMainItemIdRaw(requestParameters: GetFavoriteByMainItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Favorite>>;

    /**
     * get favorite by MainItem id
     */
    getFavoriteByMainItemId(requestParameters: GetFavoriteByMainItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Favorite>;

    /**
     * Creates request options for getFavoriteProgressByMainItemId without sending the request
     * @param {string} mainItemId 
     * @param {number} epType 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getFavoriteProgressByMainItemIdRequestOpts(requestParameters: GetFavoriteProgressByMainItemIdRequest): Promise<runtime.RequestOpts>;

    /**
     * get favorite progress (number of SubItemFavorite from the beginning) of a episode type for mainItem
     * @param {string} mainItemId 
     * @param {number} epType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getFavoriteProgressByMainItemIdRaw(requestParameters: GetFavoriteProgressByMainItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FavoriteProgress>>;

    /**
     * get favorite progress (number of SubItemFavorite from the beginning) of a episode type for mainItem
     */
    getFavoriteProgressByMainItemId(requestParameters: GetFavoriteProgressByMainItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FavoriteProgress>;

    /**
     * Creates request options for getMainItemById without sending the request
     * @param {string} id MainItem id
     * @param {string} [coverImage] populate coverImage if true
     * @param {string} [subItems] populate subItems if true
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getMainItemByIdRequestOpts(requestParameters: GetMainItemByIdRequest): Promise<runtime.RequestOpts>;

    /**
     * get a MainItem by id
     * @param {string} id MainItem id
     * @param {string} [coverImage] populate coverImage if true
     * @param {string} [subItems] populate subItems if true
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getMainItemByIdRaw(requestParameters: GetMainItemByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainItem>>;

    /**
     * get a MainItem by id
     */
    getMainItemById(requestParameters: GetMainItemByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainItem>;

    /**
     * Creates request options for getRelationsOfCharacter without sending the request
     * @param {string} id MainItem id
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getRelationsOfCharacterRequestOpts(requestParameters: GetRelationsOfCharacterRequest): Promise<runtime.RequestOpts>;

    /**
     * get all related (Item , Cast) MainItem of an Character Type MainItem.
     * @param {string} id MainItem id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getRelationsOfCharacterRaw(requestParameters: GetRelationsOfCharacterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CharacterRelationsWithMainItems>>;

    /**
     * get all related (Item , Cast) MainItem of an Character Type MainItem.
     */
    getRelationsOfCharacter(requestParameters: GetRelationsOfCharacterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CharacterRelationsWithMainItems>;

    /**
     * Creates request options for getRelationsOfItem without sending the request
     * @param {string} id MainItem id
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getRelationsOfItemRequestOpts(requestParameters: GetRelationsOfItemRequest): Promise<runtime.RequestOpts>;

    /**
     * get all related (Item, Staff, Cast, Character) MainItem of an Item Type MainItem.
     * @param {string} id MainItem id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getRelationsOfItemRaw(requestParameters: GetRelationsOfItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ItemRelationsWithMainItems>>;

    /**
     * get all related (Item, Staff, Cast, Character) MainItem of an Item Type MainItem.
     */
    getRelationsOfItem(requestParameters: GetRelationsOfItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ItemRelationsWithMainItems>;

    /**
     * Creates request options for getRelationsOfPerson without sending the request
     * @param {string} id MainItem id
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getRelationsOfPersonRequestOpts(requestParameters: GetRelationsOfPersonRequest): Promise<runtime.RequestOpts>;

    /**
     * get all related (Item , Character) MainItem of an Person Type MainItem.
     * @param {string} id MainItem id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getRelationsOfPersonRaw(requestParameters: GetRelationsOfPersonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonRelationsWithMainItems>>;

    /**
     * get all related (Item , Character) MainItem of an Person Type MainItem.
     */
    getRelationsOfPerson(requestParameters: GetRelationsOfPersonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonRelationsWithMainItems>;

    /**
     * Creates request options for getSubItemById without sending the request
     * @param {string} id SubItem Id
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getSubItemByIdRequestOpts(requestParameters: GetSubItemByIdRequest): Promise<runtime.RequestOpts>;

    /**
     * get a SubItem by id
     * @param {string} id SubItem Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getSubItemByIdRaw(requestParameters: GetSubItemByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubItem>>;

    /**
     * get a SubItem by id
     */
    getSubItemById(requestParameters: GetSubItemByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubItem>;

    /**
     * Creates request options for listFavorites without sending the request
     * @param {string} status 
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {string} [orderBy] 
     * @param {string} [sort] 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listFavoritesRequestOpts(requestParameters: ListFavoritesRequest): Promise<runtime.RequestOpts>;

    /**
     * list favorites for user
     * @param {string} status 
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {string} [orderBy] 
     * @param {string} [sort] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listFavoritesRaw(requestParameters: ListFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFavoritesResponse>>;

    /**
     * list favorites for user
     */
    listFavorites(requestParameters: ListFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFavoritesResponse>;

    /**
     * Creates request options for listMainItems without sending the request
     * @param {string} [serviceClientId] 
     * @param {string} [mainType] 
     * @param {string} [type] 
     * @param {string} [subType] 
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {string} [orderBy] 
     * @param {string} [sort] 
     * @param {string} [keyword] 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listMainItemsRequestOpts(requestParameters: ListMainItemsRequest): Promise<runtime.RequestOpts>;

    /**
     * list MainItems
     * @param {string} [serviceClientId] 
     * @param {string} [mainType] 
     * @param {string} [type] 
     * @param {string} [subType] 
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {string} [orderBy] 
     * @param {string} [sort] 
     * @param {string} [keyword] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listMainItemsRaw(requestParameters: ListMainItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListMainItemResponse>>;

    /**
     * list MainItems
     */
    listMainItems(requestParameters: ListMainItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListMainItemResponse>;

    /**
     * Creates request options for listSubItemFavorites without sending the request
     * @param {string} [itemId] itemId of the SubItem, if provided then other parameters are ignored
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {string} [orderBy] 
     * @param {string} [sort] 
     * @param {boolean} [subItem] 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listSubItemFavoritesRequestOpts(requestParameters: ListSubItemFavoritesRequest): Promise<runtime.RequestOpts>;

    /**
     * list SubItemFavorite
     * @param {string} [itemId] itemId of the SubItem, if provided then other parameters are ignored
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {string} [orderBy] 
     * @param {string} [sort] 
     * @param {boolean} [subItem] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listSubItemFavoritesRaw(requestParameters: ListSubItemFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSubItemFavoriteResponse>>;

    /**
     * list SubItemFavorite
     */
    listSubItemFavorites(requestParameters: ListSubItemFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSubItemFavoriteResponse>;

    /**
     * Creates request options for onAirItem without sending the request
     * @param {string} type type of MainItem, must be either anime or real
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    onAirItemRequestOpts(requestParameters: OnAirItemRequest): Promise<runtime.RequestOpts>;

    /**
     * get a list of on air MainItems with cover image
     * @param {string} type type of MainItem, must be either anime or real
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    onAirItemRaw(requestParameters: OnAirItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetOnAirItemListResponse>>;

    /**
     * get a list of on air MainItems with cover image
     */
    onAirItem(requestParameters: OnAirItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetOnAirItemListResponse>;

    /**
     * Creates request options for patchFavorite without sending the request
     * @param {string} id 
     * @param {PatchFavoriteBody} PatchFavoriteBody 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    patchFavoriteRequestOpts(requestParameters: PatchFavoriteRequest): Promise<runtime.RequestOpts>;

    /**
     * change status of a favorite
     * @param {string} id 
     * @param {PatchFavoriteBody} PatchFavoriteBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    patchFavoriteRaw(requestParameters: PatchFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucceedEmptyResponse>>;

    /**
     * change status of a favorite
     */
    patchFavorite(requestParameters: PatchFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucceedEmptyResponse>;

    /**
     * Creates request options for predictMainItemName without sending the request
     * @param {string} prefix start part of the name
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    predictMainItemNameRequestOpts(requestParameters: PredictMainItemNameRequest): Promise<runtime.RequestOpts>;

    /**
     * predict Main Item names base on provided prefix
     * @param {string} prefix start part of the name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    predictMainItemNameRaw(requestParameters: PredictMainItemNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * predict Main Item names base on provided prefix
     */
    predictMainItemName(requestParameters: PredictMainItemNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>>;

    /**
     * Creates request options for syncFavorites without sending the request
     * @param {SyncFavoritesRequestBody} SyncFavoritesRequestBody 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    syncFavoritesRequestOpts(requestParameters: SyncFavoritesRequest): Promise<runtime.RequestOpts>;

    /**
     * Sync favorites from external source, merge with existing favorites
     * @param {SyncFavoritesRequestBody} SyncFavoritesRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    syncFavoritesRaw(requestParameters: SyncFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SyncFavoritesResponse>>;

    /**
     * Sync favorites from external source, merge with existing favorites
     */
    syncFavorites(requestParameters: SyncFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SyncFavoritesResponse>;

    /**
     * Creates request options for syncSubItemFavoritesByFavoriteId without sending the request
     * @param {string} favoriteId 
     * @param {SyncSubItemFavoritesByFavoriteIdRequestBody} SyncSubItemFavoritesByFavoriteIdRequestBody 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    syncSubItemFavoritesByFavoriteIdRequestOpts(requestParameters: SyncSubItemFavoritesByFavoriteIdRequest): Promise<runtime.RequestOpts>;

    /**
     * sync SubItemFavorites by favorite Id
     * @param {string} favoriteId 
     * @param {SyncSubItemFavoritesByFavoriteIdRequestBody} SyncSubItemFavoritesByFavoriteIdRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    syncSubItemFavoritesByFavoriteIdRaw(requestParameters: SyncSubItemFavoritesByFavoriteIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SyncSubItemFavoritesByFavoriteIdResponse>>;

    /**
     * sync SubItemFavorites by favorite Id
     */
    syncSubItemFavoritesByFavoriteId(requestParameters: SyncSubItemFavoritesByFavoriteIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SyncSubItemFavoritesByFavoriteIdResponse>;

    /**
     * Creates request options for updateFavoriteProgress without sending the request
     * @param {string} mainItemId 
     * @param {number} progress 
     * @param {number} epType 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    updateFavoriteProgressRequestOpts(requestParameters: UpdateFavoriteProgressRequest): Promise<runtime.RequestOpts>;

    /**
     * update progress of a favorite, will create/delete SubItemFavorite
     * @param {string} mainItemId 
     * @param {number} progress 
     * @param {number} epType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    updateFavoriteProgressRaw(requestParameters: UpdateFavoriteProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucceedEmptyResponse>>;

    /**
     * update progress of a favorite, will create/delete SubItemFavorite
     */
    updateFavoriteProgress(requestParameters: UpdateFavoriteProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucceedEmptyResponse>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     * Creates request options for addClientMapping without sending the request
     */
    async addClientMappingRequestOpts(requestParameters: AddClientMappingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request_body'] == null) {
            throw new runtime.RequiredError(
                'request_body',
                'Required parameter "request_body" was null or undefined when calling addClientMapping().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/client-mapping`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['request_body'],
        };
    }

    /**
     * Add ClientMapping
     */
    async addClientMappingRaw(requestParameters: AddClientMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClientMapping>> {
        const requestOptions = await this.addClientMappingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Add ClientMapping
     */
    async addClientMapping(requestParameters: AddClientMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClientMapping> {
        const response = await this.addClientMappingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for batchGetMainItemByIdList without sending the request
     */
    async batchGetMainItemByIdListRequestOpts(requestParameters: BatchGetMainItemByIdListRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['IdListRequestBody'] == null) {
            throw new runtime.RequiredError(
                'IdListRequestBody',
                'Required parameter "IdListRequestBody" was null or undefined when calling batchGetMainItemByIdList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/client-mapping/batch/main`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['IdListRequestBody'],
        };
    }

    /**
     * get mainItems by id list
     */
    async batchGetMainItemByIdListRaw(requestParameters: BatchGetMainItemByIdListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchGetMainItemByIdListResult>> {
        const requestOptions = await this.batchGetMainItemByIdListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get mainItems by id list
     */
    async batchGetMainItemByIdList(requestParameters: BatchGetMainItemByIdListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchGetMainItemByIdListResult> {
        const response = await this.batchGetMainItemByIdListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for batchGetSubItemsByIdList without sending the request
     */
    async batchGetSubItemsByIdListRequestOpts(requestParameters: BatchGetSubItemsByIdListRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['IdListRequestBody'] == null) {
            throw new runtime.RequiredError(
                'IdListRequestBody',
                'Required parameter "IdListRequestBody" was null or undefined when calling batchGetSubItemsByIdList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/client-mapping/batch/subItem`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['IdListRequestBody'],
        };
    }

    /**
     * get SubItems by id list
     */
    async batchGetSubItemsByIdListRaw(requestParameters: BatchGetSubItemsByIdListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchGetSubItemByIdListResult>> {
        const requestOptions = await this.batchGetSubItemsByIdListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get SubItems by id list
     */
    async batchGetSubItemsByIdList(requestParameters: BatchGetSubItemsByIdListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchGetSubItemByIdListResult> {
        const response = await this.batchGetSubItemsByIdListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createFavorite without sending the request
     */
    async createFavoriteRequestOpts(requestParameters: CreateFavoriteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['Favorite'] == null) {
            throw new runtime.RequiredError(
                'Favorite',
                'Required parameter "Favorite" was null or undefined when calling createFavorite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/favorite`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['Favorite'],
        };
    }

    /**
     * create a favorite for user and item
     */
    async createFavoriteRaw(requestParameters: CreateFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Favorite>> {
        const requestOptions = await this.createFavoriteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * create a favorite for user and item
     */
    async createFavorite(requestParameters: CreateFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Favorite> {
        const response = await this.createFavoriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createSubItemFavorites without sending the request
     */
    async createSubItemFavoritesRequestOpts(requestParameters: CreateSubItemFavoritesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['CreateSubItemFavoritesRequestBody'] == null) {
            throw new runtime.RequiredError(
                'CreateSubItemFavoritesRequestBody',
                'Required parameter "CreateSubItemFavoritesRequestBody" was null or undefined when calling createSubItemFavorites().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/favorite/sub`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['CreateSubItemFavoritesRequestBody'],
        };
    }

    /**
     * create SubItemFavorites
     */
    async createSubItemFavoritesRaw(requestParameters: CreateSubItemFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSubItemFavoriteResponse>> {
        const requestOptions = await this.createSubItemFavoritesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * create SubItemFavorites
     */
    async createSubItemFavorites(requestParameters: CreateSubItemFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSubItemFavoriteResponse> {
        const response = await this.createSubItemFavoritesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteClientMappingByMainItemId without sending the request
     */
    async deleteClientMappingByMainItemIdRequestOpts(requestParameters: DeleteClientMappingByMainItemIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteClientMappingByMainItemId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/client-mapping/main/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete ClientMapping by MainItem id
     */
    async deleteClientMappingByMainItemIdRaw(requestParameters: DeleteClientMappingByMainItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteClientMappingByMainItemResponse>> {
        const requestOptions = await this.deleteClientMappingByMainItemIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Delete ClientMapping by MainItem id
     */
    async deleteClientMappingByMainItemId(requestParameters: DeleteClientMappingByMainItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteClientMappingByMainItemResponse> {
        const response = await this.deleteClientMappingByMainItemIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteFavorite without sending the request
     */
    async deleteFavoriteRequestOpts(requestParameters: DeleteFavoriteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteFavorite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/favorite/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a favorite
     */
    async deleteFavoriteRaw(requestParameters: DeleteFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucceedEmptyResponse>> {
        const requestOptions = await this.deleteFavoriteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Delete a favorite
     */
    async deleteFavorite(requestParameters: DeleteFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucceedEmptyResponse> {
        const response = await this.deleteFavoriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSubItemFavorite without sending the request
     */
    async deleteSubItemFavoriteRequestOpts(requestParameters: DeleteSubItemFavoriteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSubItemFavorite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/favorite/sub/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a SubItemFavorite
     */
    async deleteSubItemFavoriteRaw(requestParameters: DeleteSubItemFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucceedEmptyResponse>> {
        const requestOptions = await this.deleteSubItemFavoriteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Delete a SubItemFavorite
     */
    async deleteSubItemFavorite(requestParameters: DeleteSubItemFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucceedEmptyResponse> {
        const response = await this.deleteSubItemFavoriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFavoriteById without sending the request
     */
    async getFavoriteByIdRequestOpts(requestParameters: GetFavoriteByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFavoriteById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/favorite/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a favorite by id
     */
    async getFavoriteByIdRaw(requestParameters: GetFavoriteByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetFavoriteResponse>> {
        const requestOptions = await this.getFavoriteByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get a favorite by id
     */
    async getFavoriteById(requestParameters: GetFavoriteByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetFavoriteResponse> {
        const response = await this.getFavoriteByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFavoriteByMainItemId without sending the request
     */
    async getFavoriteByMainItemIdRequestOpts(requestParameters: GetFavoriteByMainItemIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFavoriteByMainItemId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/favorite/main/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get favorite by MainItem id
     */
    async getFavoriteByMainItemIdRaw(requestParameters: GetFavoriteByMainItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Favorite>> {
        const requestOptions = await this.getFavoriteByMainItemIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get favorite by MainItem id
     */
    async getFavoriteByMainItemId(requestParameters: GetFavoriteByMainItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Favorite> {
        const response = await this.getFavoriteByMainItemIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFavoriteProgressByMainItemId without sending the request
     */
    async getFavoriteProgressByMainItemIdRequestOpts(requestParameters: GetFavoriteProgressByMainItemIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mainItemId'] == null) {
            throw new runtime.RequiredError(
                'mainItemId',
                'Required parameter "mainItemId" was null or undefined when calling getFavoriteProgressByMainItemId().'
            );
        }

        if (requestParameters['epType'] == null) {
            throw new runtime.RequiredError(
                'epType',
                'Required parameter "epType" was null or undefined when calling getFavoriteProgressByMainItemId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['mainItemId'] != null) {
            queryParameters['mainItemId'] = requestParameters['mainItemId'];
        }

        if (requestParameters['epType'] != null) {
            queryParameters['epType'] = requestParameters['epType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/favorite/progress`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get favorite progress (number of SubItemFavorite from the beginning) of a episode type for mainItem
     */
    async getFavoriteProgressByMainItemIdRaw(requestParameters: GetFavoriteProgressByMainItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FavoriteProgress>> {
        const requestOptions = await this.getFavoriteProgressByMainItemIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get favorite progress (number of SubItemFavorite from the beginning) of a episode type for mainItem
     */
    async getFavoriteProgressByMainItemId(requestParameters: GetFavoriteProgressByMainItemIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FavoriteProgress> {
        const response = await this.getFavoriteProgressByMainItemIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMainItemById without sending the request
     */
    async getMainItemByIdRequestOpts(requestParameters: GetMainItemByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getMainItemById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['coverImage'] != null) {
            queryParameters['coverImage'] = requestParameters['coverImage'];
        }

        if (requestParameters['subItems'] != null) {
            queryParameters['subItems'] = requestParameters['subItems'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/public/item/main/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get a MainItem by id
     */
    async getMainItemByIdRaw(requestParameters: GetMainItemByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainItem>> {
        const requestOptions = await this.getMainItemByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get a MainItem by id
     */
    async getMainItemById(requestParameters: GetMainItemByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainItem> {
        const response = await this.getMainItemByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRelationsOfCharacter without sending the request
     */
    async getRelationsOfCharacterRequestOpts(requestParameters: GetRelationsOfCharacterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRelationsOfCharacter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/public/relation/character/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get all related (Item , Cast) MainItem of an Character Type MainItem.
     */
    async getRelationsOfCharacterRaw(requestParameters: GetRelationsOfCharacterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CharacterRelationsWithMainItems>> {
        const requestOptions = await this.getRelationsOfCharacterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get all related (Item , Cast) MainItem of an Character Type MainItem.
     */
    async getRelationsOfCharacter(requestParameters: GetRelationsOfCharacterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CharacterRelationsWithMainItems> {
        const response = await this.getRelationsOfCharacterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRelationsOfItem without sending the request
     */
    async getRelationsOfItemRequestOpts(requestParameters: GetRelationsOfItemRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRelationsOfItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/public/relation/item/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get all related (Item, Staff, Cast, Character) MainItem of an Item Type MainItem.
     */
    async getRelationsOfItemRaw(requestParameters: GetRelationsOfItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ItemRelationsWithMainItems>> {
        const requestOptions = await this.getRelationsOfItemRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get all related (Item, Staff, Cast, Character) MainItem of an Item Type MainItem.
     */
    async getRelationsOfItem(requestParameters: GetRelationsOfItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ItemRelationsWithMainItems> {
        const response = await this.getRelationsOfItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRelationsOfPerson without sending the request
     */
    async getRelationsOfPersonRequestOpts(requestParameters: GetRelationsOfPersonRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRelationsOfPerson().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/public/relation/person/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get all related (Item , Character) MainItem of an Person Type MainItem.
     */
    async getRelationsOfPersonRaw(requestParameters: GetRelationsOfPersonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonRelationsWithMainItems>> {
        const requestOptions = await this.getRelationsOfPersonRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get all related (Item , Character) MainItem of an Person Type MainItem.
     */
    async getRelationsOfPerson(requestParameters: GetRelationsOfPersonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonRelationsWithMainItems> {
        const response = await this.getRelationsOfPersonRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSubItemById without sending the request
     */
    async getSubItemByIdRequestOpts(requestParameters: GetSubItemByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSubItemById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/public/item/main/subItem/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get a SubItem by id
     */
    async getSubItemByIdRaw(requestParameters: GetSubItemByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubItem>> {
        const requestOptions = await this.getSubItemByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get a SubItem by id
     */
    async getSubItemById(requestParameters: GetSubItemByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubItem> {
        const response = await this.getSubItemByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listFavorites without sending the request
     */
    async listFavoritesRequestOpts(requestParameters: ListFavoritesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['status'] == null) {
            throw new runtime.RequiredError(
                'status',
                'Required parameter "status" was null or undefined when calling listFavorites().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['orderBy'] = requestParameters['orderBy'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/favorite`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * list favorites for user
     */
    async listFavoritesRaw(requestParameters: ListFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFavoritesResponse>> {
        const requestOptions = await this.listFavoritesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list favorites for user
     */
    async listFavorites(requestParameters: ListFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFavoritesResponse> {
        const response = await this.listFavoritesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMainItems without sending the request
     */
    async listMainItemsRequestOpts(requestParameters: ListMainItemsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['serviceClientId'] != null) {
            queryParameters['serviceClientId'] = requestParameters['serviceClientId'];
        }

        if (requestParameters['mainType'] != null) {
            queryParameters['mainType'] = requestParameters['mainType'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['subType'] != null) {
            queryParameters['subType'] = requestParameters['subType'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['orderBy'] = requestParameters['orderBy'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/public/item/main`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * list MainItems
     */
    async listMainItemsRaw(requestParameters: ListMainItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListMainItemResponse>> {
        const requestOptions = await this.listMainItemsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list MainItems
     */
    async listMainItems(requestParameters: ListMainItemsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListMainItemResponse> {
        const response = await this.listMainItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSubItemFavorites without sending the request
     */
    async listSubItemFavoritesRequestOpts(requestParameters: ListSubItemFavoritesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['itemId'] != null) {
            queryParameters['itemId'] = requestParameters['itemId'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['orderBy'] = requestParameters['orderBy'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['subItem'] != null) {
            queryParameters['subItem'] = requestParameters['subItem'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/favorite/sub`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * list SubItemFavorite
     */
    async listSubItemFavoritesRaw(requestParameters: ListSubItemFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSubItemFavoriteResponse>> {
        const requestOptions = await this.listSubItemFavoritesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * list SubItemFavorite
     */
    async listSubItemFavorites(requestParameters: ListSubItemFavoritesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSubItemFavoriteResponse> {
        const response = await this.listSubItemFavoritesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for onAirItem without sending the request
     */
    async onAirItemRequestOpts(requestParameters: OnAirItemRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling onAirItem().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/public/item/on-air`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get a list of on air MainItems with cover image
     */
    async onAirItemRaw(requestParameters: OnAirItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetOnAirItemListResponse>> {
        const requestOptions = await this.onAirItemRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * get a list of on air MainItems with cover image
     */
    async onAirItem(requestParameters: OnAirItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetOnAirItemListResponse> {
        const response = await this.onAirItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchFavorite without sending the request
     */
    async patchFavoriteRequestOpts(requestParameters: PatchFavoriteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchFavorite().'
            );
        }

        if (requestParameters['PatchFavoriteBody'] == null) {
            throw new runtime.RequiredError(
                'PatchFavoriteBody',
                'Required parameter "PatchFavoriteBody" was null or undefined when calling patchFavorite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/favorite/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['PatchFavoriteBody'],
        };
    }

    /**
     * change status of a favorite
     */
    async patchFavoriteRaw(requestParameters: PatchFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucceedEmptyResponse>> {
        const requestOptions = await this.patchFavoriteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * change status of a favorite
     */
    async patchFavorite(requestParameters: PatchFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucceedEmptyResponse> {
        const response = await this.patchFavoriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for predictMainItemName without sending the request
     */
    async predictMainItemNameRequestOpts(requestParameters: PredictMainItemNameRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prefix'] == null) {
            throw new runtime.RequiredError(
                'prefix',
                'Required parameter "prefix" was null or undefined when calling predictMainItemName().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['prefix'] != null) {
            queryParameters['prefix'] = requestParameters['prefix'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/public/item/predict`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * predict Main Item names base on provided prefix
     */
    async predictMainItemNameRaw(requestParameters: PredictMainItemNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.predictMainItemNameRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * predict Main Item names base on provided prefix
     */
    async predictMainItemName(requestParameters: PredictMainItemNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.predictMainItemNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for syncFavorites without sending the request
     */
    async syncFavoritesRequestOpts(requestParameters: SyncFavoritesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['SyncFavoritesRequestBody'] == null) {
            throw new runtime.RequiredError(
                'SyncFavoritesRequestBody',
                'Required parameter "SyncFavoritesRequestBody" was null or undefined when calling syncFavorites().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/favorite/sync`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['SyncFavoritesRequestBody'],
        };
    }

    /**
     * Sync favorites from external source, merge with existing favorites
     */
    async syncFavoritesRaw(requestParameters: SyncFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SyncFavoritesResponse>> {
        const requestOptions = await this.syncFavoritesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Sync favorites from external source, merge with existing favorites
     */
    async syncFavorites(requestParameters: SyncFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SyncFavoritesResponse> {
        const response = await this.syncFavoritesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for syncSubItemFavoritesByFavoriteId without sending the request
     */
    async syncSubItemFavoritesByFavoriteIdRequestOpts(requestParameters: SyncSubItemFavoritesByFavoriteIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['favoriteId'] == null) {
            throw new runtime.RequiredError(
                'favoriteId',
                'Required parameter "favoriteId" was null or undefined when calling syncSubItemFavoritesByFavoriteId().'
            );
        }

        if (requestParameters['SyncSubItemFavoritesByFavoriteIdRequestBody'] == null) {
            throw new runtime.RequiredError(
                'SyncSubItemFavoritesByFavoriteIdRequestBody',
                'Required parameter "SyncSubItemFavoritesByFavoriteIdRequestBody" was null or undefined when calling syncSubItemFavoritesByFavoriteId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/favorite/sync/{favoriteId}`;
        urlPath = urlPath.replace('{favoriteId}', encodeURIComponent(String(requestParameters['favoriteId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['SyncSubItemFavoritesByFavoriteIdRequestBody'],
        };
    }

    /**
     * sync SubItemFavorites by favorite Id
     */
    async syncSubItemFavoritesByFavoriteIdRaw(requestParameters: SyncSubItemFavoritesByFavoriteIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SyncSubItemFavoritesByFavoriteIdResponse>> {
        const requestOptions = await this.syncSubItemFavoritesByFavoriteIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * sync SubItemFavorites by favorite Id
     */
    async syncSubItemFavoritesByFavoriteId(requestParameters: SyncSubItemFavoritesByFavoriteIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SyncSubItemFavoritesByFavoriteIdResponse> {
        const response = await this.syncSubItemFavoritesByFavoriteIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateFavoriteProgress without sending the request
     */
    async updateFavoriteProgressRequestOpts(requestParameters: UpdateFavoriteProgressRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mainItemId'] == null) {
            throw new runtime.RequiredError(
                'mainItemId',
                'Required parameter "mainItemId" was null or undefined when calling updateFavoriteProgress().'
            );
        }

        if (requestParameters['progress'] == null) {
            throw new runtime.RequiredError(
                'progress',
                'Required parameter "progress" was null or undefined when calling updateFavoriteProgress().'
            );
        }

        if (requestParameters['epType'] == null) {
            throw new runtime.RequiredError(
                'epType',
                'Required parameter "epType" was null or undefined when calling updateFavoriteProgress().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['mainItemId'] != null) {
            queryParameters['mainItemId'] = requestParameters['mainItemId'];
        }

        if (requestParameters['progress'] != null) {
            queryParameters['progress'] = requestParameters['progress'];
        }

        if (requestParameters['epType'] != null) {
            queryParameters['epType'] = requestParameters['epType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["bookmark"]);
        }


        let urlPath = `/favorite/progress`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * update progress of a favorite, will create/delete SubItemFavorite
     */
    async updateFavoriteProgressRaw(requestParameters: UpdateFavoriteProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SucceedEmptyResponse>> {
        const requestOptions = await this.updateFavoriteProgressRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * update progress of a favorite, will create/delete SubItemFavorite
     */
    async updateFavoriteProgress(requestParameters: UpdateFavoriteProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SucceedEmptyResponse> {
        const response = await this.updateFavoriteProgressRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
