//
// AccountAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AccountAPI {
    public let apiConfiguration: MiraStreamingSDKAPIConfiguration
    public init(apiConfiguration: MiraStreamingSDKAPIConfiguration = MiraStreamingSDKAPIConfiguration.shared) {
        self.apiConfiguration = apiConfiguration
    }

    /**
     Get the current account
     
     - returns: AccountInfo
     */
    open func getAccountInfo() async throws(ErrorResponse) -> AccountInfo {
        return try await getAccountInfoWithRequestBuilder().execute().body
    }

    /**
     Get the current account
     - GET /account/info
     - Returns an empty object when the token has no corresponding account or no token is supplied.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<AccountInfo> 
     */
    open func getAccountInfoWithRequestBuilder() -> RequestBuilder<AccountInfo> {
        let localVariablePath = "/account/info"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AccountInfo>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get the legacy account name
     
     - returns: LegacyNameResponse
     */
    open func getLegacyAccountName() async throws(ErrorResponse) -> LegacyNameResponse {
        return try await getLegacyAccountNameWithRequestBuilder().execute().body
    }

    /**
     Get the legacy account name
     - GET /account/legacy/name
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<LegacyNameResponse> 
     */
    open func getLegacyAccountNameWithRequestBuilder() -> RequestBuilder<LegacyNameResponse> {
        let localVariablePath = "/account/legacy/name"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LegacyNameResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
