//
// BangumiAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class BangumiAPI {
    public let apiConfiguration: MiraStreamingSDKAPIConfiguration
    public init(apiConfiguration: MiraStreamingSDKAPIConfiguration = MiraStreamingSDKAPIConfiguration.shared) {
        self.apiConfiguration = apiConfiguration
    }

    /**
     Get a Bangumi and its episodes
     
     - parameter id: (path)  
     - returns: BangumiDetail
     */
    open func getBangumi(id: UUID) async throws(ErrorResponse) -> BangumiDetail {
        return try await getBangumiWithRequestBuilder(id: id).execute().body
    }

    /**
     Get a Bangumi and its episodes
     - GET /bangumi/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<BangumiDetail> 
     */
    open func getBangumiWithRequestBuilder(id: UUID) -> RequestBuilder<BangumiDetail> {
        var localVariablePath = "/bangumi/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BangumiDetail>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter type
     */
    public enum ModelType_getBangumiTimeline: String, Sendable, CaseIterable {
        case anime = "anime"
        case real = "real"
    }

    /**
     * enum for parameter sort
     */
    public enum Sort_getBangumiTimeline: String, Sendable, CaseIterable {
        case asc = "asc"
        case desc = "desc"
    }

    /**
     List Bangumi air dates
     
     - parameter type: (query) Omit to include all types. (optional)
     - parameter eps: (query) Exact episode-count filter. (optional)
     - parameter sort: (query)  (optional, default to .desc)
     - returns: TimelineResponse
     */
    open func getBangumiTimeline(type: ModelType_getBangumiTimeline? = nil, eps: Int? = nil, sort: Sort_getBangumiTimeline? = nil) async throws(ErrorResponse) -> TimelineResponse {
        return try await getBangumiTimelineWithRequestBuilder(type: type, eps: eps, sort: sort).execute().body
    }

    /**
     List Bangumi air dates
     - GET /bangumi/timeline
     - parameter type: (query) Omit to include all types. (optional)
     - parameter eps: (query) Exact episode-count filter. (optional)
     - parameter sort: (query)  (optional, default to .desc)
     - returns: RequestBuilder<TimelineResponse> 
     */
    open func getBangumiTimelineWithRequestBuilder(type: ModelType_getBangumiTimeline? = nil, eps: Int? = nil, sort: Sort_getBangumiTimeline? = nil) -> RequestBuilder<TimelineResponse> {
        let localVariablePath = "/bangumi/timeline"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "type": (wrappedValue: type?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "eps": (wrappedValue: eps?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort": (wrappedValue: sort?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TimelineResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter orderBy
     */
    public enum OrderBy_listBangumi: String, Sendable, CaseIterable {
        case airdate = "airDate"
    }

    /**
     * enum for parameter sort
     */
    public enum Sort_listBangumi: String, Sendable, CaseIterable {
        case asc = "asc"
        case desc = "desc"
    }

    /**
     Search and list Bangumi
     
     - parameter type: (query) TypeScript enum key used by the controller. (optional)
     - parameter subType: (query) TypeScript enum key used by the controller. (optional)
     - parameter eps: (query) Exact episode-count filter. (optional)
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query) Values outside 0 through 300 fall back to 100. (optional, default to 100)
     - parameter orderBy: (query)  (optional, default to .airdate)
     - parameter sort: (query)  (optional, default to .desc)
     - parameter keyword: (query)  (optional)
     - returns: PaginatedBangumi
     */
    open func listBangumi(type: ItemTypeQuery? = nil, subType: ItemSubTypeQuery? = nil, eps: Int? = nil, offset: Int? = nil, limit: Int? = nil, orderBy: OrderBy_listBangumi? = nil, sort: Sort_listBangumi? = nil, keyword: String? = nil) async throws(ErrorResponse) -> PaginatedBangumi {
        return try await listBangumiWithRequestBuilder(type: type, subType: subType, eps: eps, offset: offset, limit: limit, orderBy: orderBy, sort: sort, keyword: keyword).execute().body
    }

    /**
     Search and list Bangumi
     - GET /bangumi
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter type: (query) TypeScript enum key used by the controller. (optional)
     - parameter subType: (query) TypeScript enum key used by the controller. (optional)
     - parameter eps: (query) Exact episode-count filter. (optional)
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query) Values outside 0 through 300 fall back to 100. (optional, default to 100)
     - parameter orderBy: (query)  (optional, default to .airdate)
     - parameter sort: (query)  (optional, default to .desc)
     - parameter keyword: (query)  (optional)
     - returns: RequestBuilder<PaginatedBangumi> 
     */
    open func listBangumiWithRequestBuilder(type: ItemTypeQuery? = nil, subType: ItemSubTypeQuery? = nil, eps: Int? = nil, offset: Int? = nil, limit: Int? = nil, orderBy: OrderBy_listBangumi? = nil, sort: Sort_listBangumi? = nil, keyword: String? = nil) -> RequestBuilder<PaginatedBangumi> {
        let localVariablePath = "/bangumi"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "type": (wrappedValue: type?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subType": (wrappedValue: subType?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "eps": (wrappedValue: eps?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "offset": (wrappedValue: offset?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "orderBy": (wrappedValue: orderBy?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort": (wrappedValue: sort?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "keyword": (wrappedValue: keyword?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedBangumi>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter type
     */
    public enum ModelType_listOnAirBangumi: String, Sendable, CaseIterable {
        case anime = "anime"
        case real = "real"
    }

    /**
     List Bangumi airing during the current month
     
     - parameter type: (query)  
     - returns: OnAirBangumiResponse
     */
    open func listOnAirBangumi(type: ModelType_listOnAirBangumi) async throws(ErrorResponse) -> OnAirBangumiResponse {
        return try await listOnAirBangumiWithRequestBuilder(type: type).execute().body
    }

    /**
     List Bangumi airing during the current month
     - GET /bangumi/on-air
     - parameter type: (query)  
     - returns: RequestBuilder<OnAirBangumiResponse> 
     */
    open func listOnAirBangumiWithRequestBuilder(type: ModelType_listOnAirBangumi) -> RequestBuilder<OnAirBangumiResponse> {
        let localVariablePath = "/bangumi/on-air"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "type": (wrappedValue: type.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OnAirBangumiResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
