//
// FavoriteAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class FavoriteAPI {
    public let apiConfiguration: MiraStreamingSDKAPIConfiguration
    public init(apiConfiguration: MiraStreamingSDKAPIConfiguration = MiraStreamingSDKAPIConfiguration.shared) {
        self.apiConfiguration = apiConfiguration
    }

    /**
     Check whether a Bangumi is favorited
     
     - parameter bangumiId: (path)  
     - returns: FavoriteCheckResponse
     */
    open func checkFavorite(bangumiId: UUID) async throws(ErrorResponse) -> FavoriteCheckResponse {
        return try await checkFavoriteWithRequestBuilder(bangumiId: bangumiId).execute().body
    }

    /**
     Check whether a Bangumi is favorited
     - POST /favorite/check/{bangumiId}
     - Refreshes the favorite's check time when it exists.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter bangumiId: (path)  
     - returns: RequestBuilder<FavoriteCheckResponse> 
     */
    open func checkFavoriteWithRequestBuilder(bangumiId: UUID) -> RequestBuilder<FavoriteCheckResponse> {
        var localVariablePath = "/favorite/check/{bangumiId}"
        let bangumiIdPreEscape = "\(APIHelper.mapValueToPathItem(bangumiId))"
        let bangumiIdPostEscape = bangumiIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{bangumiId}", with: bangumiIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FavoriteCheckResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create or update a favorite for a Bangumi
     
     - parameter favoriteCreateRequest: (body)  
     - returns: FavoriteWithReview
     */
    open func createOrUpdateFavorite(favoriteCreateRequest: FavoriteCreateRequest) async throws(ErrorResponse) -> FavoriteWithReview {
        return try await createOrUpdateFavoriteWithRequestBuilder(favoriteCreateRequest: favoriteCreateRequest).execute().body
    }

    /**
     Create or update a favorite for a Bangumi
     - POST /favorite
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter favoriteCreateRequest: (body)  
     - returns: RequestBuilder<FavoriteWithReview> 
     */
    open func createOrUpdateFavoriteWithRequestBuilder(favoriteCreateRequest: FavoriteCreateRequest) -> RequestBuilder<FavoriteWithReview> {
        let localVariablePath = "/favorite"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: favoriteCreateRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FavoriteWithReview>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a favorite
     
     - parameter id: (path)  
     - parameter syncToUpstream: (query) Explicitly set to false to trigger the implementation&#39;s upstream deletion path. (optional)
     - returns: Void
     */
    open func deleteFavorite(id: UUID, syncToUpstream: Bool? = nil) async throws(ErrorResponse) {
        return try await deleteFavoriteWithRequestBuilder(id: id, syncToUpstream: syncToUpstream).execute().body
    }

    /**
     Delete a favorite
     - DELETE /favorite/{id}
     - The current implementation attempts upstream deletion only when `syncToUpstream=false`; omitting the parameter deletes locally only.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter syncToUpstream: (query) Explicitly set to false to trigger the implementation&#39;s upstream deletion path. (optional)
     - returns: RequestBuilder<Void> 
     */
    open func deleteFavoriteWithRequestBuilder(id: UUID, syncToUpstream: Bool? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/favorite/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "syncToUpstream": (wrappedValue: syncToUpstream?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter orderBy
     */
    public enum OrderBy_listFavorites: String, Sendable, CaseIterable {
        case updatetime = "updateTime"
        case bangumiPeriodCreatetime = "bangumi.createTime"
    }

    /**
     * enum for parameter sort
     */
    public enum Sort_listFavorites: String, Sendable, CaseIterable {
        case asc = "asc"
        case desc = "desc"
    }

    /**
     List favorites by status
     
     - parameter status: (query)  
     - parameter enableEpsUpdateTime: (query) Include the latest episode update time when available. (optional, default to false)
     - parameter countUnwatched: (query) Include each favorite&#39;s unwatched episode count. (optional, default to false)
     - parameter coverImage: (query) Populate nested Bangumi cover images. (optional, default to false)
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query) &#x60;-1&#x60; means no limit; other values outside 0 through 300 also fall back to no limit. (optional, default to -1)
     - parameter orderBy: (query)  (optional)
     - parameter sort: (query)  (optional)
     - returns: PaginatedFavorite
     */
    open func listFavorites(status: FavoriteStatus, enableEpsUpdateTime: Bool? = nil, countUnwatched: Bool? = nil, coverImage: Bool? = nil, offset: Int? = nil, limit: Int? = nil, orderBy: OrderBy_listFavorites? = nil, sort: Sort_listFavorites? = nil) async throws(ErrorResponse) -> PaginatedFavorite {
        return try await listFavoritesWithRequestBuilder(status: status, enableEpsUpdateTime: enableEpsUpdateTime, countUnwatched: countUnwatched, coverImage: coverImage, offset: offset, limit: limit, orderBy: orderBy, sort: sort).execute().body
    }

    /**
     List favorites by status
     - GET /favorite
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter status: (query)  
     - parameter enableEpsUpdateTime: (query) Include the latest episode update time when available. (optional, default to false)
     - parameter countUnwatched: (query) Include each favorite&#39;s unwatched episode count. (optional, default to false)
     - parameter coverImage: (query) Populate nested Bangumi cover images. (optional, default to false)
     - parameter offset: (query)  (optional, default to 0)
     - parameter limit: (query) &#x60;-1&#x60; means no limit; other values outside 0 through 300 also fall back to no limit. (optional, default to -1)
     - parameter orderBy: (query)  (optional)
     - parameter sort: (query)  (optional)
     - returns: RequestBuilder<PaginatedFavorite> 
     */
    open func listFavoritesWithRequestBuilder(status: FavoriteStatus, enableEpsUpdateTime: Bool? = nil, countUnwatched: Bool? = nil, coverImage: Bool? = nil, offset: Int? = nil, limit: Int? = nil, orderBy: OrderBy_listFavorites? = nil, sort: Sort_listFavorites? = nil) -> RequestBuilder<PaginatedFavorite> {
        let localVariablePath = "/favorite"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": (wrappedValue: status.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "enableEpsUpdateTime": (wrappedValue: enableEpsUpdateTime?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "countUnwatched": (wrappedValue: countUnwatched?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "coverImage": (wrappedValue: coverImage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "offset": (wrappedValue: offset?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "orderBy": (wrappedValue: orderBy?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort": (wrappedValue: sort?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedFavorite>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Replace watched episode progress from upstream favorites
     
     - parameter favoriteProgressRequest: (body)  
     - returns: Void
     */
    open func replaceFavoriteEpisodeProgress(favoriteProgressRequest: FavoriteProgressRequest) async throws(ErrorResponse) {
        return try await replaceFavoriteEpisodeProgressWithRequestBuilder(favoriteProgressRequest: favoriteProgressRequest).execute().body
    }

    /**
     Replace watched episode progress from upstream favorites
     - POST /favorite/progress
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter favoriteProgressRequest: (body)  
     - returns: RequestBuilder<Void> 
     */
    open func replaceFavoriteEpisodeProgressWithRequestBuilder(favoriteProgressRequest: FavoriteProgressRequest) -> RequestBuilder<Void> {
        let localVariablePath = "/favorite/progress"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: favoriteProgressRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Synchronize all local favorites with the upstream service
     
     - parameter overrideOnConflict: (query) Keep local values when local and upstream favorites conflict. (optional, default to false)
     - returns: Void
     */
    open func syncFavorites(overrideOnConflict: Bool? = nil) async throws(ErrorResponse) {
        return try await syncFavoritesWithRequestBuilder(overrideOnConflict: overrideOnConflict).execute().body
    }

    /**
     Synchronize all local favorites with the upstream service
     - POST /favorite/sync
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter overrideOnConflict: (query) Keep local values when local and upstream favorites conflict. (optional, default to false)
     - returns: RequestBuilder<Void> 
     */
    open func syncFavoritesWithRequestBuilder(overrideOnConflict: Bool? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/favorite/sync"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "overrideOnConflict": (wrappedValue: overrideOnConflict?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update a favorite's status
     
     - parameter id: (path)  
     - parameter status: (query)  
     - parameter syncToUpstream: (query) Set to false to skip synchronization with the upstream Mira service. (optional, default to true)
     - returns: FavoriteSummary
     */
    open func updateFavoriteStatus(id: UUID, status: FavoriteStatus, syncToUpstream: Bool? = nil) async throws(ErrorResponse) -> FavoriteSummary {
        return try await updateFavoriteStatusWithRequestBuilder(id: id, status: status, syncToUpstream: syncToUpstream).execute().body
    }

    /**
     Update a favorite's status
     - PUT /favorite/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter status: (query)  
     - parameter syncToUpstream: (query) Set to false to skip synchronization with the upstream Mira service. (optional, default to true)
     - returns: RequestBuilder<FavoriteSummary> 
     */
    open func updateFavoriteStatusWithRequestBuilder(id: UUID, status: FavoriteStatus, syncToUpstream: Bool? = nil) -> RequestBuilder<FavoriteSummary> {
        var localVariablePath = "/favorite/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": (wrappedValue: status.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "syncToUpstream": (wrappedValue: syncToUpstream?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FavoriteSummary>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
